### ISSUE TITLE
Enhanced Feature: Sending POI address instead of GPS coordinates

### ISSUE THREAD

**Issue by rikroe** [bimmerconnected/bimmer_connected#104]
As mentioned in a comment in [#66](https://github.com/m1n3rva/bimmer_connected/issues/66#issuecomment-483829190) and #103, I tried to implement the option to send address data only to BMW, without the need of specifying GPS coordinates. That failed 🎉 

When sending POI data without GPS coordinates, the API responds with `204` and the car shows the message with a correctly formatted address. However the option to navigate somewhere is missing. This field only shows up when **GPS coordinates are provided as well**. 

I confirmed that for navigation only the GPS coordinates are relevant. When I send an address ~20 km away but coordinates ~500 km away, the car apparently reverse geocodes the GPS coordinates, although the message information said differently. Fun fact: as soon as some of this "display information" is sent to the car, the GPS coordinates in the message will disappear.

So the big question is: **Do we want to reverse geocode address data to GPS coordinates in bimmer_connected?** 
If yes, I could for example try to implement ``geopy`` using [OSM Nominatim](https://wiki.openstreetmap.org/wiki/Nominatim). 
If no, this is fine for me as well. As I want to send POIs from my Home Assistant instance, I would  use a RESTful Command to get the GPS coordinates and only propagates those (with the additional display data) to bimmer_connected. 

Looking forward to your opinions (or even better suggestions) 😄

**Comment by shr00mie** [comment]
Was sitting on the shutter, read this, and my immediate thought was...

OH HEY. ZONES!

While not the perfect solution due to their somewhat static nature, more often than not, you're probably going places you've been before.

In HA, zones have a human name, but are drawn using lat/lon and radius.

could probably leverage that in either drop-down form or expose zones to Google Assistant, for example, and use the zones to send lat/lon as POIs to the car...

then again, this could just be a...shitty idea...

🙃

**Comment by rikroe** [comment]
Haha that's an awesome idea! Let's hope @m1n3rva finds the time to incorporate the open pull requests, then I'd see if I am able to integrate this into HA :)

**Comment by gerard33** [comment]
Will have a look at these PR's.

> So the big question is: Do we want to reverse geocode address data to GPS coordinates in bimmer_connected?

Let's implement that on HA side in not in this library.

**Comment by gps1539** [comment]
Hi

It looks to be fairly simple to get long & lat from an address via geocoder. No API key required by OSM. 

`#!/usr/bin/env python3

import geocoder

g = (geocoder.osm('Avaya Stadium, San Jose, California')).osm
print (g)
long=(g["x"])
lat=(g["y"])

print(long, lat)`

If someone can point in the right direction on the BMW API I'm happy to test this on my BMW i3
Thanks all for writing bimmerconnected.

**Comment by robthebold** [comment]
> Hi
> 
> It looks to be fairly simple to get long & lat from an address via geocoder. No API key required by OSM.
> 
> ```
> #!/usr/bin/env python3
> 
> import geocoder
> 
> g = (geocoder.osm('Avaya Stadium, San Jose, California')).osm
> print (g)
> long=(g["x"])
> lat=(g["y"])
> 
> print(long, lat)
> ```
> 
> If someone can point in the right direction on the BMW API I'm happy to test this on my BMW i3
> Thanks all for writing bimmerconnected.

Looks very promising!  If you git the project code (plus the changes in PR #103) you should be able to test this out. Plug the geolocation values you retrieve from geocoder into vehicle.sendpoi and you can see how well it works. I've been playing with this using values I get from google maps and other sources.

**Comment by gps1539** [comment]
Thanks I will give it a go. 
1st time working on another project, would you recommend I set up virtualenv as a sandbox?

**Comment by gps1539** [comment]
Struggling to create an environment that works with your changes. I pulled bimmer-connected-0.6.0 but when I try running your updates I get ImportError: ,,,,
Where should I clone from?

**Comment by gps1539** [comment]
I made some progress and found I can call OSM API directly and avoid needing the geocoder module as it may be hard to install for some OSes. Will need urllib.request, but I think that is pretty common.

I can get the lat and lon for an address and send to my car and it matches when I check messages on the car. Still working on the name part and currently showing up as 'null' on the car, but I think I know why.

**Comment by gerard33** [comment]
Great progress :+1:

You can fork the bimmerconnected repo, implemented the changes you made and push the changes to that repo. From there you can make a PR to bimmerconnected.

**Comment by gps1539** [comment]
I can fork the sendpoi branch and add my changes there.

**Comment by gps1539** [comment]
Hi, anything I need to do with my PR or do I just need to be patient ?

**Comment by gerard33** [comment]
Yeah sorry, I am quite busy so I have to find some time to review the PR.
But the submit looks good.

@robthebold Could you test this code as well to see if everything works for your car?

**Comment by gps1539** [comment]
Cheers, I've used it several times to send POIS to my car and it has been working well. I have not got lost yet :-)

**Comment by robthebold** [comment]
I think merging this pull request requires first -- or simultaneously -- merging #103 and that PRs changes to vehicle.py, including the addition of the pointofinterest class and associated code. Otherwise there'll be an import error. 

Also, I may be a little dense, but I'm not figuring out the format of address to use.

when I try your example: 
`cli.py sendpoi  -n 49ers -a 4900 Marie P DeBartolo Way, Santa Clara, CA username password region VIN` where of course username etc. has the real values . . . 
I get
`error: the following arguments are required: username, password, region, vin`
What have I misinterpreted?

**Comment by gps1539** [comment]
try ./cli.py sendpoi username password region VIN  -n 49ers -a 4900 Marie P DeBartolo Way, Santa Clara, CA 

I think the other arguments are positional. I think we could fix that with flags i.e. -u --user, -p --password etc.

**Comment by rikroe** [comment]
Hey guys, cool work with OSM and sorry for being quiet for some time...

I think the best way would be first merging #98, then #103 and lastly #115. This should go through without the need of any additional merging/branching. 

I have a local work-in-progress for rebuilding cli.py with click and that uses the GMaps API (there are some 300$ free), but that is nowhere complete... 

So great that we move forward to merge this, hopefully we can update the HA package then soon as well :)

**Comment by robthebold** [comment]
"Are you ready for some football?", that's the syntax that works.  1500 mile road trip! Gets sent correctly to my i3.

Do you think it's worthwhile to modularize the geocode functionality. I know it's only 8 lines of code, but it provides an important function that doesn't quite fit in the rest of the modules (vehicle, account, etc.). That might make the ultimate integration into the HA component easier on that side.

Also, I think rikroe's recommended order of merges is the right way to do it.

**Comment by rikroe** [comment]
I think it is always worthwhile to modularize something :) However it really depends on how the functionality is used in the end. 

To me, there are two types of using the SendPoi functionality: a) by using cli.py or b) by importing PointOfInterest directly in python code. 

For quickly using the functionality, a) is fine to me. For b), we are modular enough right now. However the question remains if we want to reverse geocode adresses im bimmer_connected when importing the module e.g. in HA. Thing is, there are python libraries for geocoding, but most services require API keys etc. (I think you even have to be careful with OSM, see [here](https://operations.osmfoundation.org/policies/nominatim/)).

It could make sense to move the PointOfInterest Class to its own python file and there devise a converter with multiple functions (e.g. `poi_from_osm()`, `poi_from_gmaps()`and of course `poi()`(manually)).

However we could start with this in a two-step approach: bring the basic functionality in (#98 and #103) and add the possibility for cli usage (#115). Maybe HA even provides some reverse-geocoding functionality that could be used more or less directly in the component? bimmer_connected would then only do the handling of the BMW api calls.

**Comment by gps1539** [comment]
Glad the POI code seems to be working. Apart from sending a POI to our cars what else do you see this being useful for?

I originally looked at using a geocode library module but I wanted to avoid creating another dependency for folks to have to install. Using OSM's APIs is fairly simple and while they do have a fair usage policy that looks to be open for use cases like ours.

**Comment by rikroe** [comment]
This is needed only for sending POIs to our cars. The question ist just how we get the information.

I really like your implementation because it is generally usable. My setup differs a little bit, I share a POI from Google maps via telegram to HA and have a script that parses the coords and Infos from the maps URL. As this requires API credentials I'm not sure if it is possible to implement directly in bimmerconnected. 
Therefore I just want to make sure that there is always to possibility to use the raw send poi implementation without much else. 

OSM is fine, I just had in mind that they were requesting a specific user agent and might block on it. Just don't know how many people would use this solution in the end (and how OSM counts 1 request/sec) but it should be fine for A start.

**Comment by robthebold** [comment]
> Maybe HA even provides some reverse-geocoding functionality that could be used more or less directly in the component? bimmer_connected would then only do the handling of the BMW api calls.

Interesting . . . I hadn't even thought to look into that in existing HA components (or whatever components are called now, "integrations" I think?).

A two-phase rollout seems reasonable. And ultimately exposing the address lookup functionality in the HA connected drive component will be a real plus for users there, I think, :)

**Comment by rikroe** [comment]
I'd appreciate a two-phase rollout :) However I'd be glad if you can wait a day or two for merging...

I found a way to remove the dreaded `null` in the message 🎉 It was a simple as adding some information to `additionalInfo`...
With a day or two I would like to make the PointOfInterest class type-safe (same types as BMW APIs) and add some (at least basic) tests. 

Will update my PR (#103) accordingly.

![IMG_20191006_103525](https://user-images.githubusercontent.com/42204099/66266699-bab0de00-e828-11e9-834b-fb7075a4109e.jpg)

**Comment by gerard33** [comment]
Great stuff!
I will wait for your updated PR before merging the related PRs.
Good to see all the improvements you guys make to the library 👍🏻

**Comment by rikroe** [comment]
So, got more time than expected today and updated my PR.

@gps1539 @robthebold as you two have been testing the previous version as well, please check with the current one. For a quick test, you just need get the [vehicle.py from my branch](https://raw.githubusercontent.com/rikroe/bimmer_connected/sendpoi/bimmer_connected/vehicle.py) and replace your local version with it. Should be working without issues.

**Comment by gps1539** [comment]
I can retest with the vehicle.py from your branch tomorrow.

**Comment by robthebold** [comment]
> I found a way to remove the dreaded `null` in the message  It was a simple as adding some information to `additionalInfo`...

Excellent! I'd been trying to fill out fields for a while with absolutely zero success.

> as you two have been testing the previous version as well, please check with the current one. For a quick test, you just need get the [vehicle.py from my branch](https://raw.githubusercontent.com/rikroe/bimmer_connected/sendpoi/bimmer_connected/vehicle.py) and replace your local version with it. Should be working without issues.

I'll be doing some testing today.

**Comment by gps1539** [comment]
Tested with the updated vehicle.py and sending POI works and now has the "Sent with (heart) from bimmer_connect ;-) 
I also successfully check my i3's state of charge with the same update.

**Comment by robthebold** [comment]
Tested it out with @rikroe's latest vehicle.py. Looks good.

**Comment by gps1539** [comment]
Hi, wondering if it makes sense to add flags for each argument so position would not matter such as -u/--user, -p/--password etc. As @robthebold found when trying my PR position currently needs to be in the right order.

**Comment by rikroe** [comment]
> wondering if it makes sense to add flags for each argument

I totally agree with you. However I'm not sure how many people are using bimmer_connected from cli. For all of those this would be a breaking change which I wouldn't opt for easily...

**Comment by gps1539** [comment]
Good point, that could break it for others.

**Comment by robthebold** [comment]
As long as its syntax is properly spelled out in the use/help text, I think it'll be ok. The cli seems to me to primarily serve those who need a terminal app for testing purposes or for scripting calls to the library from the command line or from another application.  Correct me if I'm wrong in my assumptions, but I do agree it's best not to break anything unnecessarily.

**Comment by rikroe** [comment]
To get this a little cleaned up, I've created another issue. Due to the long time of this issue and the corresponding PRs I'd hope to get the (working) SendPoi functionality merged as is.

Then all of @swimsystems PRs for code cleanup and tests and then we should have a good base to start further development.

**Comment by gerard33** [comment]
Thanks. Will have a look at the PRs this week. Bit busy so didn’t have time for it yet.

**Comment by rikroe** [comment]
Closed by #164.
