### ISSUE TITLE
debug log text copy/paste error in remote_services.py module

### ISSUE THREAD

**Issue by robthebold** [bimmerconnected/bimmer_connected#106]
In module remote_services.py, the procedures trigger_remote_door_unlock and trigger_remote_horn both log incorrect debugging text due to a simple copy/paste oversight. It appears that the _unlock_ procedure message was copied from the remote lock procedure without changing "lock" to "unlock". Remote horn text was copy/pasted from _light flash_ without changing text.

**Comment by gerard33** [comment]
Merged via PR #105.
