### ISSUE TITLE
BMW F35 3-series [328Li] 2016 fingerprint data [CHINA]

### ISSUE THREAD

**Issue by freeznet** [bimmerconnected/bimmer_connected#107]
[status_0.txt](https://github.com/m1n3rva/bimmer_connected/files/3279471/status_0.txt)
[vehicles_0.txt](https://github.com/m1n3rva/bimmer_connected/files/3279472/vehicles_0.txt)

the connected service was expired early this year so most of connected service are "NOT_SUPPORTED". hoping this data is useful ;) and thanks again for this cool project.

**Comment by gerard33** [comment]
Thanks will have a look at this and add it to the other fingerprint data.

**Comment by gerard33** [comment]
Thanks! Added the responses to the data set.
