### ISSUE TITLE
get_vehicle_image fails when direction = REARBIRDSEYE (2017 i3+Rex)

### ISSUE THREAD

**Issue by robthebold** [bimmerconnected/bimmer_connected#109]
The get_vehicle_image function in vehicle.py can take direction values from the enum class VehicleViewDirection, which is defined as:

`class VehicleViewDirection(Enum):
    """Viewing angles for the vehicle.

    This is used to get a rendered image of the vehicle.
    """
    FRONTSIDE = 'FRONTSIDE'
    FRONT = 'FRONT'
    REARSIDE = 'REARSIDE'
    REAR = 'REAR'
    SIDE = 'SIDE'
    DASHBOARD = 'DASHBOARD'
    DRIVERDOOR = 'DRIVERDOOR'
    REARBIRDSEYE = 'REARBIRDSEYE'
`

But server returns a 404 for my i3 when direction is REARBIRDSEYE. Other direction values get valid images back. (I wrote a little test script to call the function for various directions.)

`Unknown status code 404, expected 200
{"error":{"code":500,"description":"(SmartPhoneUtil-A-2012) Ressource not found. No image available for VIN WBYXXXXXXXXXXXX"}}
Traceback (most recent call last):
  File "./motorlaunch.py", line 326, in <module>
    main()
  File "./motorlaunch.py", line 242, in main
    get_image(configdir,vehicle,VehicleViewDirection(views[index-1]))
  File "./motorlaunch.py", line 299, in get_image
    image_data = vehicle.get_vehicle_image(640,480,direction)
  File "/home/rob/.local/lib/python3.5/site-packages/bimmer_connected/vehicle.py", line 159, in get_vehicle_image
    response = self._account.send_request(url, headers=header)
  File "/home/rob/.local/lib/python3.5/site-packages/bimmer_connected/account.py", line 136, in send_request
    raise IOError(msg)
OSError: Unknown status code 404, expected 200
`

I've only got the one car to test on. Is REARBIRDSEYE not valid for all models? Is REARBIRDSEYE not valid on any? Is it a typo? Is it not valid for the image size I used?

**Comment by gerard33** [comment]
Will check if it works with my car.

**Comment by robthebold** [comment]
Anybody else seen this issue on their vehicle? On have it working?
