### ISSUE TITLE
BMW server not returning final response on remote services

### ISSUE THREAD

**Issue by robthebold** [bimmerconnected/bimmer_connected#110]
I'm testing this in the US with a '17 i3 with Rex.

The functions in remote_services that expect a final response from the BMW server are not getting one and timing out instead. These services are: lock, unlock, climatize, honk and flash.  IIRC, this problem didn't exist several months ago, so I suspect a change in function on BMW's side.

A typical error looks like this:

```
Traceback (most recent call last):
  File "/home/rob/motorlaunch/motorlaunch.py", line 372, in <module>
    main()
  File "/home/rob/motorlaunch/motorlaunch.py", line 230, in main
    vehicle.remote_services.trigger_remote_air_conditioning()
  File "/home/rob/motorlaunch/bimmer_connected/remote_services.py", line 121, in trigger_remote_air_conditioning
    result = self._block_until_done(_Services.REMOTE_AIR_CONDITIONING)
  File "/home/rob/motorlaunch/bimmer_connected/remote_services.py", line 142, in _block_until_done
    status = self._get_remote_service_status(service)
  File "/home/rob/motorlaunch/bimmer_connected/remote_services.py", line 162, in _get_remote_service_status
    response = self._account.send_request(url)
  File "/home/rob/motorlaunch/bimmer_connected/account.py", line 136, in send_request
    raise IOError(msg)
OSError: Unknown status code 502, expected 200

```

I tried increasing 
`_POLLING_TIMEOUT = 600
`
...from the default of 60 in remote_services.py, but even a 10 minute delay is too short.

(motorlaunch.py is an interactive script I've been using to save typing while testing bimmer_connected features requiring frequent typing of account names and passwords and VINs and regions, etc.)

I don't know if perhaps the block_until_done approach is no longer valid -- if it is I don't know how one would know the services request was received and properly acted upon . . . so I don't have a good solution to offer.

**Comment by shr00mie** [comment]
getting the same.

based on the [US site](https://connecteddrive.bmwusa.com), i have a feeling they're finally migrating over to whatever the new incarnation of the service is. the UI is entirely different.

the mobile app has been erroring out of the gate. had to uninstall/reinstall so i could log in. upon login, no vehicle was linked to my account (it is on the website), and when i tried adding it manually via the mobile app, it asked for primary/secondary driver and then said the vehicle was already added to the account.

i have a feeling they got shit pointing all over the place and the cutover isn't complete or they have a ton of bugs to work out on their end, at which point the API urls might need to be modified, assuming it still works and token process is the same.

**Comment by basilfx** [comment]
I have the same problems with `rest_of_world` with an i3 94Ah (2017). The response I get (when using the CLI), shows this:

```
ERROR:bimmer_connected.account:Unknown status code 502, expected 200
ERROR:bimmer_connected.account:<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/spuWebAPI/api/v1/user/vehicles">GET&nbsp;/spuWebAPI/api/v1/user/vehicles</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p></p>
<p>Additionally, a 502 Bad Gateway
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

Traceback (most recent call last):
  File "/opt/apps/homeassistant/env/bin/bimmerconnected", line 126, in <module>
    main()
  File "/opt/apps/homeassistant/env/bin/bimmerconnected", line 45, in main
    args.func(args)
  File "/opt/apps/homeassistant/env/bin/bimmerconnected", line 76, in fingerprint
    log_responses=time_dir)
  File "/opt/apps/homeassistant/env/lib/python3.7/site-packages/bimmer_connected/account.py", line 55, in __init__
    self._get_vehicles()
  File "/opt/apps/homeassistant/env/lib/python3.7/site-packages/bimmer_connected/account.py", line 191, in _get_vehicles
    logfilename='vehicles')
  File "/opt/apps/homeassistant/env/lib/python3.7/site-packages/bimmer_connected/account.py", line 135, in send_request
    raise IOError(msg)
OSError: Unknown status code 502, expected 200
```

**Comment by robthebold** [comment]
As of tonight, 1:35 on Sept 6 UTC, BMW north america servers are responding properly and in a timely fashion.

Of course, anything that gets better on its own can get broken on its own again, so we'll see . . .

**Comment by robthebold** [comment]
It's now September 13 and the server is still responding properly. Since nothing on the Bimmerconnected side has been done to fix this, I guess the answer is that it was BMW's server's problem all along. I think I'm going to close this issue. If it recurs, we'll still have the observations here to refer back to . . . If anyone's got a different experience, post please.
