### ISSUE TITLE
tls issues after updating to debian buster

### ISSUE THREAD

**Issue by gweiss76** [bimmerconnected/bimmer_connected#111]
Hi

After updating to Debian buster bimmer_connected is unable to establish a ssl connection to "b2vapi.bmwgroup.com".
The error message i get here is:
requests.exceptions.SSLError: HTTPSConnectionPool(host='b2vapi.bmwgroup.com', port=443): Max retries exceeded wit                                               h url: /gcdm/oauth/token (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.                                               c:1056)')))

As the error "SSL: UNSUPPORTED_PROTOCOL" seems weird to me i investigated further.
It seems that b2vapi.bmwgroup.com only supports TLSv1.0
-> https://www.ssllabs.com/ssltest/analyze.html?d=b2vapi.bmwgroup.com

Also the openssl version packaged in Debian Buster has TLSv1.0 Support disabled by default.
-> https://lists.debian.org/debian-devel-announce/2017/08/msg00004.html

**Comment by gerard33** [comment]
Is your HA instance running on Debian Buster and the component can't get the data from the BMW Connected Drive portal anymore?

**Comment by OliverRepo** [comment]
It started working for me after allowing TLSv1.0 in my container:

`sed -i "s|TLSv1.2|TLSv1.0|g" /etc/ssl/openssl.cnf` 

However, that is not a great fix for this issue.

**Comment by gerard33** [comment]
Not a great fix indeed, but seems to be the only solution as long as the BMW CD portal only supports TLS v1.0.

**Comment by sanderlv** [comment]
> It started working for me after allowing TLSv1.0 in my container:
> 
> `sed -i "s|TLSv1.2|TLSv1.0|g" /etc/ssl/openssl.cnf`
> 
> However, that is not a great fix for this issue.

How and where did you do this? Can you please help me in the right direction?
