### ISSUE TITLE
Missing 0.5.6 on pypi

### ISSUE THREAD

**Issue by pvizeli** [bimmerconnected/bimmer_connected#113]
We revert the update of 0.5.6 because the version is missed now on pypi.

**Comment by gerard33** [comment]
That’s correct, v0.5.6 had an issue so I removed it (I only saw the version was bumped in HA after the PR was merged).

I am working on an updated version and on a PR for HA which I want to have ready for the next beta.

**Comment by gerard33** [comment]
Fixed via https://github.com/home-assistant/home-assistant/pull/26098.
