### ISSUE TITLE
Range Map

### ISSUE THREAD

**Issue by robthebold** [bimmerconnected/bimmer_connected#116]
BMW Connected Drive supports a range map (at least for electric vehicles) that shows an isoline indicating maximum range for current state of charge

I'd like to display this range map in graphic form

mapbox.com provides a facility to draw an isoline on a map. I've tested the mapbox solution with BMW connecteddrive rangemap data and it provides a useful at-a-glance visualization of electric vehicle range. Other mapping solutions may be available as well.

It might make the most sense to do the map display on the HA side rather than the bimmerconnected library. But in any case, the data is available and can be plotted in a useful fashion.

I don't know if this feature is available on ICE or mild hybrid vehicles. I've only investigated it on my i3 with Rex.

**Comment by robthebold** [comment]
![image](https://user-images.githubusercontent.com/38596885/65888670-87240e80-e365-11e9-8805-6fb4a93c41f4.png)

Here's what we can get from the car:

Two arrays of lat, long points, 50 points each, 1st and last points are the same. One array labeled COMFORT, the other ECO_PRO_PLUS. There's a field in the json called "quality," it's always AVERAGE in my testing, and other for "center". The center point and the "polyline" are required to render the rangemap with mapbox. These points can be plugged into an html file which is submitted to mapbox for rendering via a browser.

The maps seems to be of lower resolution (if that's the right word) than the rangemap on the in-car nav screen. This one is more blobby, while the in-car one is much more starburst like. Perhaps if "quality" were something better than "AVERAGE" we'd get more points, but I haven't figured that out.

If we were to do this for a lot of cars, we'd need to do something about the mapbox api key other than using the general public one, I think.

**Comment by gerard33** [comment]
It's a nice feature but you indeed need something like HA to show the map. This library can only deliver that data, not showing it on a map.

**Comment by robthebold** [comment]
I agree with you @gerard33. . . . _And_ the code I was testing to retrieve the info got broken by BMW in the last few months anyway. :(
