### ISSUE TITLE
Show car location in online map

### ISSUE THREAD

**Issue by gps1539** [bimmerconnected/bimmer_connected#120]
Hi

I think we could add the ability to show the location of a car in OpenStreetMap using the lat, lon from the status response and using something like webbrowser.open('https://www.openstreetmap.org/export#map=20/lat/lon')

If this sounds interesting I'm happy to prototype it.

**Comment by rikroe** [comment]
Where would you like to see the map? In your own website? In HomeAssistant? Somewhere else?
I'm asking as this library basically does only the backend (which then is used by a [HomeAssistant component](https://github.com/home-assistant/home-assistant/tree/dev/homeassistant/components/bmw_connected_drive). 

If you'd like to see a map in HomeAssistant, you probably need to figure out how HA's map card for their Lovelace UI works and adapt that. 
Or implement the current car position as HomeAssistant `device_tracker` entity - then you could use the existing map in HA.

If you want to have it independently, we probably need another separate project which provides the HTML part and is able to call the backend python code.

**Comment by gps1539** [comment]
I was thinking of something much simpler and just open a tab on the local client's (PC, laptop) browser and display the car's location. Similar to the way the BMW connected app (on android) can show the position on google maps.

**Comment by robthebold** [comment]
I think in homeassistant you just have to add the map: component and you can see devices listed in device_tracker. including connected drive vehicles.

If you'd like to see location of your car from the cli, you could pass the latitude and longitude values to your favorite mapping site or application.

So, for instance, I've been playing around with the bimmer_connected library on my sailfish phone. The python lines:
`command = '{} geo:{},{} &'.format(mapper, vehicle.state.gps_position[0],vehicle.state.gps_position[1])
os.system(command)`
will open the app with the name defined in "mapper" that takes lat and lon as arguments to show the vehicle position in the center of the map.

**Comment by gerard33** [comment]
@gps1539 In HA you can already show the location of your car on a map -> https://www.home-assistant.io/lovelace/map.
I am using this:
```yaml
- type: map
  # dark_mode: true
  aspect_ratio: 100%
  default_zoom: 14
  entities:
    - device_tracker.x1_sdrive18i
```

This map will show the position of your car (also when it is at home) using Openstreetmap.

Is your use case in something else then HA?

**Comment by gps1539** [comment]
My use case was nothing as fancy as HA, just to open a browser with a page showing the cars location based on the lon lat we get from status. 

something like
webbrowser.open('https://www.openstreetmap.org/?mlat=53.9027&mlon=-1.2717#map=12/53.9027/-1.2717&layers=C')

Should show your car is in a field in Northern England, and you could use OSM to get directions to find it.

**Comment by rikroe** [comment]
Ah I see. You could certainly use or modify the output of cli.py to do such a think (opening a http request).
But then you would only get the current position once (no updates etc but that seems to be be fine). 
Also, you would need a PC/Laptop/whatever device capable of running Python 3 to do this calculation, so no quick check on the phone (correct me if I'm wrong here). Supposed you want to access it on the fly, you'd again need a web app etc. with authorization or hidden behind some VPN service.

**Comment by gerard33** [comment]
Can we close this one? I don't see this as part of the library.

**Comment by robthebold** [comment]
This would be a nice feature for an application using this library, but not necessarily as a feature of the library itself. So, I would agree closing is ok.
