### ISSUE TITLE
Remove positional arguments from CLI

### ISSUE THREAD

**Issue by rikroe** [bimmerconnected/bimmer_connected#122]
As discussed in #104, there can be issues and misunderstandings when using positional parameters. The proposed solution would be to change all positional arguments to named arguments.

This issues serves as a todo in case we want to work on it.

**Comment by zpeters** [comment]
I'd like to contribute to this if it is still something you want to do

**Comment by rikroe** [comment]
Great! Just be patient for a couple of days, there are some PRs that need to be merged (and probably conflicts solved) :)

**Comment by zpeters** [comment]
am i okay to start working on this now?  Sorry i lost track of this issue

**Comment by gerard33** [comment]
@rikroe Can we close this?

**Comment by rikroe** [comment]
Yeah, I would be fine closing this.
