### ISSUE TITLE
Invalid config:  bmw-connected-drive could not be set up

### ISSUE THREAD

**Issue by jolaca01** [bimmerconnected/bimmer_connected#123]
**Describe the issue**
Even if my username, password and region have not changed, my BMW connected drive HA integration does not work anymore. 

**Expected behavior**
I expected to have my BMW connected-drive data available for HA because of having set up this integration and because it had been working without any issue in the past. I've tried restarting HA many times, but nothing. 

**Home Assistant version**
I am using 0.100.1 HA version but, it doesn't seem to work since 3 or even more older versions. 

**Screenshots**
![image](https://user-images.githubusercontent.com/18713946/66719896-fbdf5a00-edf5-11e9-96a3-0b40d937f3fe.png)

**Your config.yaml**

```
bmw_connected_drive:
  name: 
    username: !secret bmw_username
    password: !secret bmw_password
    region: "rest_of_world"
```

> Log Details (ERROR)
> Sun Oct 13 2019 19:53:36 GMT+0200 (hora de verano de Europa central)
> Error during setup of component bmw_connected_drive
> Traceback (most recent call last):
>   File "/srv/homeassistant/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 472, in wrap_socket
>     cnx.do_handshake()
>   File "/srv/homeassistant/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1915, in do_handshake
>     self._raise_ssl_error(self._ssl, result)
>   File "/srv/homeassistant/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
>     _raise_current_error()
>   File "/srv/homeassistant/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
>     raise exception_type(errors)
> OpenSSL.SSL.Error: [('SSL routines', 'ssl_choose_client_version', 'unsupported protocol')]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/srv/homeassistant/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
>     chunked=chunked)
>   File "/srv/homeassistant/lib/python3.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
>     self._validate_conn(conn)
>   File "/srv/homeassistant/lib/python3.7/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
>     conn.connect()
>   File "/srv/homeassistant/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
>     ssl_context=context)
>   File "/srv/homeassistant/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
>     return context.wrap_socket(sock, server_hostname=server_hostname)
>   File "/srv/homeassistant/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 478, in wrap_socket
>     raise ssl.SSLError('bad handshake: %r' % e)
> ssl.SSLError: ("bad handshake: Error([('SSL routines', 'ssl_choose_client_version', 'unsupported protocol')])",)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/srv/homeassistant/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
>     timeout=timeout
>   File "/srv/homeassistant/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen

bmw_connected_drive:
  name_of_car:
    username: USERNAME_BMW_CONNECTED_DRIVE
    password: PASSWORD_BMW_CONNECTED_DRIVE
    region: one of "north_america", "china" , "rest_of_world"
````
Thank you very much for your help. I really appreciate your work and help. I've tried to solve my issue on the community forum without luck. 


**Output of bimmer_connected fingerprint**
If you have run the [bimmer_connected fingerprint](https://github.com/bimmerconnected/bimmer_connected#data-contributions) please share that data here

*NOTE: It might take me awhile to repond on GitHub (I only maintain this in my free time), but I will respond.*

**Comment by robthebold** [comment]
The communication code hasn't changed in the bimmerconnected library, so your regional BMW servers may have changed as a result of a bug on intentionally. I see you're in the rest_of_world region, what country are you in? Do you use the BMW phone app, and if so is it having any problems?

**Comment by jolaca01** [comment]
Thanks for your answer. Yep, I set up  rest_of_world region because I live in Spain, and it used to work flawlessly. I can connect without issues to BMW connected site but also without issues to the BMW connected phone app.

**Comment by gerard33** [comment]
Did you upgrade to Debian Buster?
Check issue #111 for a solution.

**Comment by jolaca01** [comment]
Thank you very much!! Indeed, I'd upgraded to Debian Buster, now I've followed the issue #111 solution to allow TLS1.0 and everything's working again!! Thank you again!!
