### ISSUE TITLE
Test new Connected Drive url

### ISSUE THREAD

**Issue by gerard33** [bimmerconnected/bimmer_connected#130]
@rikroe made a new issue to be able to track the progress better then in #99.

> Sure, I've updated the [python gist](https://gist.github.com/rikroe/ea4ae264e124f4a7c672ae6e35b7d83b). Works standalone as python script and only needs `requests` installed.
> 
> @robthebold could you do a quick check as well if the general setup allows also for US-based ConnectDrive accounts?
> 
> If it works for you, I will take on the task to update the current URLs and `account.py` to use the new APIs (including token storage and renewal).

_Originally posted by @rikroe in https://github.com/bimmerconnected/bimmer_connected/issues/99#issuecomment-546328559_

**Comment by robthebold** [comment]
Just to make sure this info is easily visible in this new separate issue I'm duplicate my report that it tests OK for US servers.

**Comment by gerard33** [comment]
Great work! I have run the script and get valid vehicleStatus data for my car (The Netherlands).

**Comment by rikroe** [comment]
Thanks guys, hope to get some work done on the weekend, at least finishing the oauth process and storage.

**Comment by gerard33** [comment]
Closing this issue, part of PR #140.
