### ISSUE TITLE
Remote heating status

### ISSUE THREAD

**Issue by odelma** [bimmerconnected/bimmer_connected#132]
Hi,

is the remote heating status (on, off, scheduled, remaining time) available through the API? If it is, could it be added to this librarby?

**Comment by gerard33** [comment]
You can activate the remote climate as mentioned [here](https://www.home-assistant.io/integrations/bmw_connected_drive/#services). Scheduling can also be done via HA automations. Status is not available (as far as I know).

**Comment by odelma** [comment]
Yes, turning it on works great but it would have been great to get the status as well (if it is on or off - and the remaining heating time). We also have a Volkswagen and the VW WeConnect service gives this info so I was wondering would it be available from ConnectedDrive. How about setting the scheduled leave time?

**Comment by robthebold** [comment]
Reading and setting the weekly and one-time departure times is supported by the protocol and is gonna get added to this library. I _don't_ know of a way of checking that status of pre-conditioning, whether it's on or off and its estimated complete time. AFAICT, this isn't in the known functionality of the connected drive protocal.

**Comment by robthebold** [comment]
PR #137 adds some functionality to test out these features. So far, the charging profile parsing is extremely naive. See definition of structure [here](https://github.com/edent/BMW-i-Remote#charging-schedule) for some definitions. I'm not sure what features are unique to vehicles with electric drivetrains and which are more general, so I'm interested in what happens for ICE only cars, too.

**Comment by gerard33** [comment]
Closing this, feel free to open a new issue if this is still relevant.
