### ISSUE TITLE
Real-time on/off update?

### ISSUE THREAD

**Issue by jiiins** [bimmerconnected/bimmer_connected#135]
**Is your feature request related to a problem? Please describe.**
I'm trying to record the company car's utilization in real-time (via Home Assistant) but I can't find a way to get the information in a timely manner. The phone app seems to be updating immediately when the car is turned on, but I can't get that info anywhere.

**Describe the solution you'd like**
Real-time GPS position would be great, but I assume is not possible. The next best thing would be to know when a car leaves a place (gets turned on and starts moving) and when it gets turned off (and where).

**Describe alternatives you've considered**
I don't know how the BMW service works and I can't find any information (I looked!). So I'm not sure of what is possible. Can a car be dynamically queried for its position every minute or so? How often is the car sending data on its own and how often can we query the server for such updates?

*NOTE: It might take me a while to respond on GitHub (I only maintain this in my free time), but I will respond.*

Thanks a lot for your work!!

**Comment by odelma** [comment]
Hi,

when comparing this script to some other alternatives there is something strange with the update intervals. I have used in parallel a fork from this: https://github.com/jupe76/bmwcdapi/blob/master/bmwcdapi.py which is found here: https://pastebin.com/5KsXMtFb (discussion: https://forums.indigodomo.com/viewtopic.php?f=138&t=21369&sid=b9915cf8367f943b00b7f58340606892&start=15) and quite often I've noticed that bimmer_connected update timestamp is from a few to several hours ago while the data collected via the other script is quite recent. Maybe @gerard33 could give us a comment on this - are we doing something "wrong" to get older data with bimmer_connected when comparing to e.g. bmwcdapi?

**Comment by jiiins** [comment]
Anyone knows if it's possible to pull the on/off status in real-time?

**Comment by gerard33** [comment]
The car data is only available for this library when the car is turned off (no ignition). When the car is driving, there is no new data shown, so it's not possible to use the device tracker data in real-time. The app showing the updates of the location instantly must be because it's using the GPS of the phone.
