### ISSUE TITLE
NoneType' object has no attribute 'value' for door_lock_state

### ISSUE THREAD

**Issue by fierland** [bimmerconnected/bimmer_connected#145]
Log Details (ERROR)
Sun Dec 15 2019 23:57:58 GMT+0100 (Central European Standard Time)
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 408, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 286, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 328, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/lock.py", line 64, in device_state_attributes
    "door_lock_state": vehicle_state.door_lock_state.value,
AttributeError: 'NoneType' object has no attribute 'value'

[status_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/3965570/status_0.txt)
[vehicles_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/3965571/vehicles_0.txt)

**Comment by robthebold** [comment]
Is this another example of assuming an attribute exists that isn't really returned from connected_drive like in issues #129,  #141, & #142?

But this shouldn't happen in this case, should it? The door_lock_state shouldn't be in the attributes. The vehicles.txt file shows lscType=NOT_SUPPORTED. That shouldn't pass this test:

`       if self.lsc_type in [LscType.LSC_BASIS, LscType.I_LSC_IMM, LscType.LSC_PHEV]:
`

in available_attributes in vehicle.py, right?

**Comment by gerard33** [comment]
The reasons this fails is that the HA integration currently not checks for the `available _attributes`, in this case `door_lock_state` when adding the lock component.
So the lock is added for unsupported cars, causing this error. I will make a PR in HA to fix this.

**Comment by gerard33** [comment]
Fixed in PR https://github.com/home-assistant/core/pull/32074.
