### ISSUE TITLE
Current API shutoff?

### ISSUE THREAD

**Issue by janhaa** [bimmerconnected/bimmer_connected#150]
The current used API host seems to have stopped working, I only get 400 although it worked fine over weeks.

Looking at the BMW Portal I also see requests to a to me previously unknown API host:

`https://customer.bmwgroup.com/gcdm/oauth/authenticate`

Related to https://github.com/bimmerconnected/bimmer_connected/pull/140 ?

The oauth code can be found here: https://customer.bmwgroup.com/one/app/oauth.js (mirrored to https://pastebin.com/1y6ULKrr)

**Comment by janhaa** [comment]
The oauth code can be found here: https://customer.bmwgroup.com/one/app/oauth.js

**Comment by janhaa** [comment]
This code allows me to retrieve vehicles again: https://gist.github.com/janhaa/0547a1f7934df58358826c4ea9631da7

**Comment by deluxestyle** [comment]
I‘m using home assistant with the bmw component which based on bimmer connect. I’m also not able to connect anymore. 
Do you know how to get your fix into it?

**Comment by quentinsf** [comment]
So would it be a case of just changing AUTH_URL in const.py to https://customer.bmwgroup.com/gcdm/oauth/authenticate
?

(Sorry, I don't have a machine handy on which I can easily experiment with this.)

**Comment by janhaa** [comment]
@quentinsf Unfortunately they changed the whole process of connecting. I think a fix is in the work though.

**Comment by deluxestyle** [comment]
@janhaa thank you. Do you know if still someone is working on it? Seems to be quite silent since a month

**Comment by rikroe** [comment]
Seems like BMW finally changed their APIs (server and path prefix). We tried to implement it in #140 but then stopped due to the new code only working for rest_of_world vehicles, i.e. US (and probably) China vehicles still needed to use the old API.

Unfortunately this code stopped working as well, so we're back to the scratchpad.

Using the Web API at bmw-connecteddrive.com would be an option (at least easier to reverse-engineer), but the mobile phone API proides much more data.

**Comment by Timo47v** [comment]
@rikroe You can use the method from @janhaa's example to get your access token and use it with the old API. However, you need to make 1 modification: the scope must also include `remote_services vehicle_data`. The old API checks for this when it verifies your access token.

**Comment by rikroe** [comment]
Thats an amazing catch, thanks! Didn't do that transfer there! PR incoming.

**Comment by woody438** [comment]
I second the HA integration (not hass.io) - thx!

**Comment by rs38** [comment]
if you add the "fupo" scope the token will also work for the "web page API"?

**Comment by edlea** [comment]
> the mobile phone API proides much more data

The mobile API was also _proper_ OAuth and gave us refresh tokens, meaning we didn't need to do anything with the user's password other than send it to BMW. Unless I'm mistaken, the web API requires us to store the user's password to make requests after the initial token expires (2 hours?)
