### ISSUE TITLE
Install instruction

### ISSUE THREAD

**Issue by nottledim** [bimmerconnected/bimmer_connected#160]
It would be really helpful (for those at the bottom of the learning curve) if there were a couple of lines in the README on how to install this software.  
"See bimmerconnected for usage instruction" is not very helpful.  What does it mean?

**Comment by rikroe** [comment]
Basically it means you're supposed to execute `python -m bimmer_connected.cli` on the command line and you'll get the available available options.

You of course need python 3.5+ installed and either install this library via `pip` or `git clone`.

Is this the kind of help you would expect?

**Comment by nottledim** [comment]
Yes, if that does the trick. Or pip install ...
