### ISSUE TITLE
Give device tracker other name in case of multiple cars from same model

### ISSUE THREAD

**Issue by gerard33** [bimmerconnected/bimmer_connected#162]
See https://github.com/home-assistant/core/issues/29976

**Comment by gerard33** [comment]
Will be fixed in https://github.com/home-assistant/core/pull/35732.

**Comment by rikroe** [comment]
Bump, we're still waiting on HA PR merge.

**Comment by gerard33** [comment]
Closing this one. Is part of https://github.com/home-assistant/core/pull/39585.
