### ISSUE TITLE
Add VEHICLE_FINDER service

### ISSUE THREAD

**Issue by droneando** [bimmerconnected/bimmer_connected#182]
Hi:
Many thanks for your project!

I have missed in your project the VEHICLE_FINDER service, that forces the vehicle to update its gps position on the BMW servers. At least in my vehicle (2015 F31), if you don't force the vehicle finder in the BMW app, this data is not updated automatically and the last location you requested remains.

The ideal would be to create a service that from time to time (could be 1, 2, 3 ... hours) runs the VEHICLE_FINDER service so that the location of the vehicle is always updated.

I have tried to make a simple modification in your code to test by CLI if it works, and yes, it works.

Thank you!

**Comment by gerard33** [comment]
Can you share the code for `VEHICLE_FINDER` that you have tested?

**Comment by droneando** [comment]
Shure!
Finally I made modifications to some files to create a new service in Home Assistant, called bmw_connected_drive.find_vehicle, to be able to run it from a button in lovelace or create an automation to run every 2 hours.
The modified files are:

cli.py
`def main() -> None:
...
finder_parser = subparsers.add_parser('vehiclefinder', description='update the vehicle gps location')
    _add_default_arguments(finder_parser)
    finder_parser.add_argument('vin', help='vehicle identification number')
    finder_parser.set_defaults(func=vehicle_finder)
...`

`def vehicle_finder(args) -> None:
    """Trigger the vehicle finder to locate it."""
    account = ConnectedDriveAccount(args.username, args.password, get_region_from_name(args.region))
    vehicle = account.get_vehicle(args.vin)
    if not vehicle:
        valid_vins = ", ".join(v.vin for v in account.vehicles)
        print('Error: Could not find vehicle for VIN "{}". Valid VINs are: {}'.format(args.vin, valid_vins))
        return
    status = vehicle.remote_services.trigger_remote_vehicle_finder()
    print(status.state)`

remote_serices.py:
`class _Services(Enum):
    """Enumeration of possible services to be executed."""
    REMOTE_LIGHT_FLASH = 'LIGHT_FLASH'
    REMOTE_VEHICLE_FINDER = 'VEHICLE_FINDER'
    REMOTE_DOOR_LOCK = 'DOOR_LOCK'
    REMOTE_DOOR_UNLOCK = 'DOOR_UNLOCK'
    REMOTE_HORN = 'HORN_BLOW'
    REMOTE_AIR_CONDITIONING = 'CLIMATE_NOW'`

`class RemoteServices:
    """Trigger remote services on a vehicle."""
...
def trigger_remote_vehicle_finder(self) -> RemoteServiceStatus:
        """Trigger the vehicle finder.

        A state update is triggered after this, as the location state of the vehicle changes.
        """
        _LOGGER.debug('Triggering remote vehicle finder')
        # needs to be called via POST, GET is not working
        self._trigger_remote_service(_Services.REMOTE_VEHICLE_FINDER, post=True)
        result = self._block_until_done(_Services.REMOTE_VEHICLE_FINDER)
        self._trigger_state_update()
        return result
...`

And in .../site-packages/homeassistant/components/bmw_connected_drive:

__init__.py:
`_SERVICE_MAP = {
    "light_flash": "trigger_remote_light_flash",
    "sound_horn": "trigger_remote_horn",
    "activate_air_conditioning": "trigger_remote_air_conditioning",
    "find_vehicle": "trigger_remote_vehicle_finder",
}`

services.yaml:
`find_vehicle:
  description: >
    Request vehicle to update his gps location. The vehicle is identified via the vin
    (see below).
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: WBANXXXXXX1234567`

The mod integration is running flawesly from yesterday, either from automation every 2 hours, or from a button that I created in Lovelace.

What I'm missing now is a sensor in Home Assistant that shows me the execution state of the last remote service called, because some times the BMW servers fails to execute them, because server saturation or not being able to contact the vehicle. So if execution fails I could handle it by calling again the remote service.

**Comment by gerard33** [comment]
@rikroe can you test this with your car?

**Comment by rikroe** [comment]
Copied the code from @droneando, works flawlessly on my 2013 F31 (see PR).

Many thanks for the code! Using HA will require changes to the component to have it included.

**Comment by gerard33** [comment]
Nice work @droneando. This is a good addition to the library.
Thanks for testing and making the PR @rikroe.

**Comment by gerard33** [comment]
Let's keep this one open until the PR for HA is ready 😄

**Comment by gerard33** [comment]
The PR for HA is merged in https://github.com/home-assistant/core/pull/36985.
