### ISSUE TITLE
History of attribute charging_time_remaining becomes integer

### ISSUE THREAD

**Issue by licheng5625** [bimmerconnected/bimmer_connected#184]
**Describe the issue**
 history of charging time remaining becomes integer.  MINI countryman PHEV
![image](https://user-images.githubusercontent.com/10073591/83355068-413ca180-a35d-11ea-86d6-309e7c00a2c2.png)

**Expected behavior**

Before the format was H:MM:SS. Now it becomes to 3, 2,or 1. 

**Home Assistant version**

Home Assistant 0.110.4

It works in previous version, but I forgot the version id.

**Connected Drive website**

If you see any issues with the BMW integration in Home Assistant (or when directly using the library), please make sure to first login to the BMW Connected Drive website of your country and check if you can successfully login and query the car status.
- [x] I can still successfully login to the BMW Connected Drive website and the car status is available there.
- [x] I have Connected Drive enabled for my vehicle.

**Number of cars**

If you have more than 1 car please mention that here.
- [x] I have a Mini vehicle linked to my account.

**Comment by gerard33** [comment]
Closing this issue as from the library perspective this works as expected.
