### ISSUE TITLE
Which Web API to use?

### ISSUE THREAD

**Issue by weymann** [bimmerconnected/bimmer_connected#193]
I'm developing a PlugIn for the Home Automation system _openhab_ in order to integrate my BMW i3. I didn't find an email connection here so I decided to open Issue. I hope this is fine for you.

I have a question and I hope you can give me some advice. Looking into your code I can see queries towards **%BMW_SERVER%/webapi/v1**. Another developer placed a different api in his code namely **%BMW_SERVER%/api/vehicle**. You can find it [here](https://github.com/jupe76/bmwcdapi/blob/master/bmwcdapi.py).

As far as I can see with different calls both APIs are delivering nearly the same data. While webapi delivers messages like "Next Services" in english api/vehicle delivers this in german which is my mother tongue. But this isn't a big issue.

So my question is if you have any recommendation which one to use. Perhaps one is older and will get outdated?

Any advice is helpful!
Thanks!

**Comment by gerard33** [comment]
Thanks for your message and sure it's no problem to open an issue 😄

We have started with `api/vehicle` as well, but changed that to `webapi/v1` shortly after the integration went live in HA to support users from USA and Canada.

**Comment by weymann** [comment]
Ok, so as I understand`webapi/v1` is supported worldwide. This is surely a big plus!

I see that you're currently dealing only with `status` query. Do you also have some experience regarding  `/statistics/lastTrip` and `/statistics/allTrips` especially for Vehicles with different Drivetrains?

**Comment by gerard33** [comment]
See this PR -> https://github.com/bimmerconnected/bimmer_connected/pull/191

**Comment by weymann** [comment]
Works like a charm, only for rangemap I've some issues. Looking into the code rangemap is called with parameters "dlat", "dlon" and "deviceTime". Performing this call Server Respond with 500 - Internal Server Error

https://b2vapi.bmwgroup.com/webapi/v1/user/vehicles/ANONYMOUS/rangemap?dlat=47%2E573105&dlon=7%2E664435&deviceTime=2020%2D09%2D02T14%3A17%3A28 

Is this query working on your side?

**Comment by gerard33** [comment]
Don't know, but the PR is just merged, so maybe you can test it with this library?
