### ISSUE TITLE
Message format for navigation

### ISSUE THREAD

**Issue by nderooij** [bimmerconnected/bimmer_connected#203]
Hi All,

I'm using this integration to send messages to my car (2015, F20) from my home automation system (Home Assistant). I would love to include addresses, so I can have my home automation server send addresses automatically to my car's navigation.

I know I can do this manually from the app and that if I open the app while USB connected to my car it can check my calendar. But I would love to just get the message send to my car automatically either in the beginning of the day or for example an hour before.

My "problem" is that the message comes in, but the flag icon to start navigation stays greyed out.

Thank you!

**Comment by gerard33** [comment]
Have you checked the documentation? -> https://www.home-assistant.io/integrations/bmw_connected_drive/#send-a-point-of-interest-to-your-vehicle

**Comment by nderooij** [comment]
> Have you checked the documentation? -> https://www.home-assistant.io/integrations/bmw_connected_drive/#send-a-point-of-interest-to-your-vehicle

Ouch... I did, but not sure how I missed this... Guess I just need to find an easy way to convert address in to coordinates, but I’ll find out :)

Sorry for wasting your time dude! I owe you a beer for this one...

**Comment by gerard33** [comment]
Haha no problem 😉
You can use Google Maps to get the lat/lon of an address. Just right click on the position on the map and then on Wat is hier?.
