### ISSUE TITLE
State is missing

### ISSUE THREAD

**Issue by 0rsa** [bimmerconnected/bimmer_connected#206]
Hello,

I wrote this simple code:

`
from bimmer_connected.account import ConnectedDriveAccount
from bimmer_connected.country_selector import Regions

from pprint import pprint

account = ConnectedDriveAccount(MY_MAIL, MY_PASSWORD, Regions.REST_OF_WORLD)
vehicle = account.get_vehicle(MY_VIN)
state = vehicle.state
pprint(vars(state))
`

State attributes are empty, please find below script output:
`{'_account': <bimmer_connected.account.ConnectedDriveAccount object at 0x000002E519926FD0>,
 '_attributes': {},
 '_vehicle': <bimmer_connected.vehicle.ConnectedDriveVehicle object at 0x000002E51C2ABDC0>}`

Am I missing something ?

Model F60/Mini (Mini Countryman All4 Hybrid 2019)

Thank you

**Comment by rikroe** [comment]
You'll need to update/download the vehicle's states before using `account.update_vehicle_states()`.

**Comment by 0rsa** [comment]
Thank you
