### ISSUE TITLE
Add horn to cli command

### ISSUE THREAD

**Issue by martinorob** [bimmerconnected/bimmer_connected#212]
I’m not able to trigger remote horn using the cli

usage: bimmerconnected [-h]                       {status,fingerprint,lightflash,vehiclefinder,image,sendpoi,sendpoi_from_address,sendmessage}

i’m missing some information about cli usage?

Thanks

**Comment by gerard33** [comment]
The horn command is not part of the bimmerconnected cli.
You should be able to add it there rather easy by re-using the `light_flash` function.

**Comment by martinorob** [comment]
It worked! Thank you!
