### ISSUE TITLE
Question: definition of username

### ISSUE THREAD

**Issue by gabrielke** [bimmerconnected/bimmer_connected#215]
Please explain the following connection parameters a bit more straightforward in the documentation
"name:" shall by replaced by my userid in homeassistant like "gabriel" or by my username "Gabriel Akos" ?
Same for the "username:" parameter, shall it be an e-mail like "xy@gmail.com" or the username shown in the connected drive site?

Ah, in the bugreport template I see instead of "name:" it is already "name_of_car:" 
HomeAssistant version: 0.116.4

Thanks!

**Comment by rikroe** [comment]
Hi, you're referencing `name` in the context of the [HA documentation](https://www.home-assistant.io/integrations/bmw_connected_drive#configuration)?
If so, that would be your ConnectedDrive user name, i.e. the email address.

**Comment by gabrielke** [comment]
No, the e-mail address is to be written in the "username:" field.
There is a tag name: above (one higher in the yaml hierarchy)

**Comment by rikroe** [comment]
Ah, that's more of an arbitrary name you can set on your own, I think it is never used in the code (and of course should be described as such).

When https://github.com/home-assistant/core/pull/39585 is merged in HomeAssistant (probably with 0.118) then the entries in configuration.yaml will get deprecated and not used anymore.
Therefore I rather wouldn't revisit this before.

**Comment by gerard33** [comment]
It's correct what rikroe mentions above. You can put the name of your car in there, but indeed it's never used. Probably some leftover from another approach choosen earlier.

**Comment by gabrielke** [comment]
Checked with 0.117 and the name field set to 330e the entities appear as sensor.330e_... and work just perfectly.

**Comment by gerard33** [comment]
The integration uses the model from the BMW API in the naming of the entity_ids.
I have the following config
```yaml
bmw_x1:
  username: !secret bimmer_user
  password: !secret bimmer_pass
  region: rest_of_world
```

So `bmw_x1` as the `name`, but my entity_ids are like this `sensor.x1_sdrive18i_...`
The `x1_sdrive18i` is the model we get from the BMW API -> https://github.com/bimmerconnected/bimmer_connected/blob/master/test/responses/vehicles.json#L63.
In your case that model is the same as the name you set, but that's a coincidence 😀
