### ISSUE TITLE
F30 330e 2016 fingerprint 

### ISSUE THREAD

**Issue by gabrielke** [bimmerconnected/bimmer_connected#216]
**Describe the issue**

HomeAssistant tells at startup that this integration failed to start.
I found this exception in the log:

homeassistant_1  | 2020-10-24 23:41:18 ERROR (SyncWorker_5) [bimmer_connected.account] Authentication failed. Maybe your password is invalid?
homeassistant_1  | 2020-10-24 23:41:18 ERROR (SyncWorker_5) [bimmer_connected.account] ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

Since the "standalone" code works  (see data below) I guess the code in the home-assistant version connects to the "old" BMW endpoints.

**Expected behavior**

HomeAssistant can start with this integration.

**Home Assistant version**

0.116.4

And did it work on a previous version, if so what was the last working version?

Not tried with previous version.

**Connected Drive website**

If you see any issues with the BMW integration in Home Assistant (or when directly using the library), please make sure to first login to the BMW Connected Drive website of your country and check if you can successfully login and query the car status.
- [ x] I can still successfully login to the BMW Connected Drive website and the car status is available there.
- [ x] I have Connected Drive enabled for my vehicle.

**Output of bimmer_connected fingerprint**

{
  "vehicleStatus": {
    "DCS_CCH_Activation": "NA",
    "DCS_CCH_Ongoing": false,
    "cbsData": [
      {
        "cbsDescription": "Next statutory vehicle inspection due by the stated date.",
        "cbsDueDate": "2020-12",
        "cbsState": "OK",
        "cbsType": "VEHICLE_TUV"
      },
      {
        "cbsDescription": "Next service due when the stated distance has been covered or by the specified date.",
        "cbsDueDate": "2021-01",
        "cbsRemainingMileage": 8000,
        "cbsState": "OK",
        "cbsType": "OIL"
      },
      {
        "cbsDescription": "Next change due at the latest by the stated date.",
        "cbsDueDate": "2021-10",
        "cbsState": "OK",
        "cbsType": "BRAKE_FLUID"
      },
      {
        "cbsDescription": "Next visual inspection due when the stated distance has been covered or by the stated date.",
        "cbsDueDate": "2023-01",
        "cbsRemainingMileage": 40000,
        "cbsState": "OK",
        "cbsType": "VEHICLE_CHECK"
      }
    ],
    "chargingConnectionType": "CONDUCTIVE",
    "chargingLevelHv": 100,
    "chargingStatus": "FINISHED_FULLY_CHARGED",
    "checkControlMessages": [],
    "connectionStatus": "CONNECTED",
    "doorDriverFront": "CLOSED",
    "doorDriverRear": "CLOSED",
    "doorLockState": "SECURED",
    "doorPassengerFront": "CLOSED",
    "doorPassengerRear": "CLOSED",
    "hood": "CLOSED",
    "internalDataTimeUTC": "2020-10-24T20:57:54",
    "lastChargingEndReason": "UNKNOWN",
    "lastChargingEndResult": "FAILED",
    "maxRangeElectric": 19,
    "maxRangeElectricMls": 11,
    "mileage": 79864,
    "parkingLight": "OFF",
    "position": {
      "heading": 123,
      "status": "OK"
    },
    "positionLight": "OFF",
    "rearWindow": "CLOSED",
    "remainingFuel": 10,
    "remainingRangeElectric": 19,
    "remainingRangeElectricMls": 11,
    "remainingRangeFuel": 133,
    "remainingRangeFuelMls": 82,
    "singleImmediateCharging": false,
    "trunk": "CLOSED",
    "updateReason": "CHARGING_PAUSED",
    "updateTime": "2020-10-24T20:57:54+0000",
    "vehicleCountry": "HU",
    "vin": "some_vin",
    "windowDriverFront": "CLOSED",
    "windowDriverRear": "CLOSED",
    "windowPassengerFront": "CLOSED",
    "windowPassengerRear": "CLOSED"
  }
}

{
  "vehicles": [
    {
      "a4a": "BLUETOOTH",
      "bodytype": "F30",
      "brand": "BMW",
      "breakdownNumber": "+4989358957103",
      "carCloud": "NOT_SUPPORTED",
      "chargeNow": "NOT_SUPPORTED",
      "chargingControl": "NOT_SUPPORTED",
      "chargingUpdateMode": "NORMAL_PROGNOSE_BASED",
      "climateControl": "NOT_SUPPORTED",
      "climateControlRES": "NOT_SUPPORTED",
      "climateFunction": "AIRCONDITIONING",
      "climateNow": "ACTIVATED",
      "climateNowRES": "NOT_SUPPORTED",
      "color": "CHAMPAGNER QUARZ METALLIC",
      "colorCode": "X08",
      "countryCode": "B1-CS-HU",
      "dealer": {
        "city": "Budapest",
        "country": "HU",
        "name": "Budapest Motors Kft",
        "phone": "+36 1 2266363",
        "postalCode": "1033",
        "street": "Szentendrei ut 63."
      },
      "doorLock": "ACTIVATED",
      "doorUnlock": "ACTIVATED",
      "driveTrain": "PHEV",
      "egoVehiclePath": "",
      "hasAlarmSystem": true,
      "hmiVersion": "ID5",
      "hornBlow": "ACTIVATED",
      "hub": "HUB_ECE",
      "intermodalRouting": "NOT_AVAILABLE",
      "ipa": "NOT_SUPPORTED",
      "lastDestinations": "NOT_SUPPORTED",
      "licensePlate": "some_license_plate",
      "lightFlash": "ACTIVATED",
      "lscType": "LSC_PHEV",
      "model": "330e iPerformance",
      "onlineSearchMode": "MAP",
      "onlineSearchProvider": "GOOGLE",
      "puStep": "1119",
      "rangeMap": "NOT_SUPPORTED",
      "remote360": "NOT_SUPPORTED",
      "remoteSoftwareUpgrade": "NOT_SUPPORTED",
      "sendPoi": "ACTIVATED",
      "smartSolution": "NOT_SUPPORTED",
      "statisticsAvailable": true,
      "statisticsCommunityEnabled": false,
      "steering": "LH",
      "supportedChargingModes": [
        "AC_LOW"
      ],
      "vehicleFinder": "ACTIVATED",
      "vehicleFinderRestriction": "NONE",
      "vin": "some_vin",
      "yearOfConstruction": 2016
    }
  ]
}

**Comment by gerard33** [comment]
The issue in HA you see is solved and will be part of HA 0.117 -> https://github.com/home-assistant/core/issues/42256

The reason that the fingerprint works is that it already uses the latest version of the library.

**Comment by gabrielke** [comment]
Cool, thanks, I'll give it a try anr report back here.

**Comment by gabrielke** [comment]
Checked 0.117 right now and works perfectly, thanks!
