### ISSUE TITLE
Add new services for PHEV/EVs to HA

### ISSUE THREAD

**Issue by gerard33** [bimmerconnected/bimmer_connected#224]
Regarding integration of these new services in HA: i made some progress already.
Sneak preview:
[
![53AEFBC2-832F-459E-BB29-7DB69489AC7F](https://user-images.githubusercontent.com/13943630/97805456-8ccde100-1c56-11eb-9090-04683aca025d.jpeg)
](url)

Work in progress for All_Trips & Charging_Profile. 
@gerard33  @rikroe When i’m done, should i do a PR to HA core or do i have to wait until the new bimmer_connected has been bumped to a newer version?

_Originally posted by @EddyK69 in https://github.com/bimmerconnected/bimmer_connected/pull/191#issuecomment-720097579_

**Comment by gerard33** [comment]
Thats looking great, many thanks!

Please create a PR to HA when your done, just two thing to keep in mind: 
- We have to publish a new release of the library before (so no beta release in manifest.json) and I would like to clean some little things up - hope I have the chance this week.
- Probably you have to wait until the config flow PR is merged into HA - this should be done latest with 0.118 so you do not have that many changes.

_Originally posted by @rikroe in https://github.com/bimmerconnected/bimmer_connected/pull/191#issuecomment-720107195_

**Comment by gerard33** [comment]
@gerard33 Here my fingerprint files....
[bmw_i3.zip](https://github.com/bimmerconnected/bimmer_connected/files/5464872/bmw_i3.zip)

Note that the RangeMap didn't work: Error 500. Made a PR #219 to fix unhandled exception on the request

_Originally posted by @EddyK69 in https://github.com/bimmerconnected/bimmer_connected/pull/191#issuecomment-719506285_

**Comment by gerard33** [comment]
@EddyK69 Let us know if you want us to review the changes you made before making a PR to HA (after the points mentioned above by rikroe).

**Comment by odelma** [comment]
Looks great! :smile:
I'm using bimmerconnected through the cli - does this mean the "status" command should contain these values in the future or there might be some other commands to retrieve the new information?

**Comment by rikroe** [comment]
The `status` command should include these values. However I am not sure if you will get one single JSON output or multiple JSONs in one string.
If the latter, it probably is just some changes in the `cli` code.

**Comment by EddyK69** [comment]
> @gerard33 Here my fingerprint files....
> [bmw_i3.zip](https://github.com/bimmerconnected/bimmer_connected/files/5464872/bmw_i3.zip)
> 
> Note that the RangeMap didn't work: Error 500. Made a PR #219 to fix unhandled exception on the request
> 
> _Originally posted by @EddyK69 in [#191 (comment)](https://github.com/bimmerconnected/bimmer_connected/pull/191#issuecomment-719506285)_

Had a 200 for retrieving the RangeMap today! (my first this week)
`{
  "rangemap": {
    "center": {
      "lat": 12.3456,
      "lon": 34.5678
    },
    "rangemaps": [
      {
        "radius": 169
      }
    ]
  }
}` 

note that my vehicle has
`"rangeMap": "RANGE_POLYGON"`

**Comment by EddyK69** [comment]
> The `status` command should include these values. However I am not sure if you will get one single JSON output or multiple JSONs in one string.
> If the latter, it probably is just some changes in the `cli` code.

Via the cli, all new services report their status in one single JSON string

**Comment by EddyK69** [comment]
> @EddyK69 Let us know if you want us to review the changes you made before making a PR to HA (after the points mentioned above by rikroe).

@gerard33 All set! See my branche here: https://github.com/EddyK69/core/tree/prepare_for_bmw_connectedrive_update
Would you please be so kind to review?

![last_trip](https://user-images.githubusercontent.com/13943630/97861772-9150d300-1d04-11eb-9803-3a85ddeee2f7.png)
![all_trips](https://user-images.githubusercontent.com/13943630/97861250-c01a7980-1d03-11eb-8434-ebcd3c1efc61.png)
![charging_profile](https://user-images.githubusercontent.com/13943630/97861264-c27cd380-1d03-11eb-8b81-8d852ddf4f44.png)
![destinations](https://user-images.githubusercontent.com/13943630/97861589-4c2ca100-1d04-11eb-9d5b-728be186e7b4.png)

**Comment by rikroe** [comment]
To make it easier to test and see your changes, you could also develop against the custom component at https://github.com/bimmerconnected/ha_custom_component on `master`. I've just rebased the code there to home-assistant/core#39585.

**Comment by EddyK69** [comment]
Thnx, but I already tested it against the 0.7.10 release :)

**Comment by rikroe** [comment]
Great!

Yeah, the rebase is one PR ahead of the current HA release but that will hopefully merged with 0.118. Rebased to it because it contains some general changes to all components and a complete rewrite of the device tracker due to now being configured via UI.

**Comment by gerard33** [comment]
@EddyK69  was just going to post the message above from rikroe 😁

> @gerard33 All set! See my branch here: https://github.com/EddyK69/core/tree/prepare_for_bmw_connectedrive_update
Would you please be so kind to review?

This is indeed based on the current, but soon to be old, version in HA. If you could make your changes based on the config_flow PR from rikroe, then we can review that directly in the right version.

**Comment by EddyK69** [comment]
> If you could make your changes based on the config_flow PR from rikroe, then we can review that directly in the right version.

@gerard33 Sure, wil prepare this somewhere this week 👍

**Comment by EddyK69** [comment]
Made PR to ha_custom_components repos:
https://github.com/bimmerconnected/ha_custom_component/pull/5

Note: gps_heading in device_tracker is todo, hence not in dimmer_connected yet...

**Comment by gerard33** [comment]
Will have a look at your PR next week.

**Comment by EddyK69** [comment]
Would be great if it could be released in HA 0.118 😁

**Comment by gerard33** [comment]
That would be great indeed, but that's unlikely.
First the config_flow PR needs to be merged, that has not happened yet, so the question is of that will be in 0.118 as the beta cuts tomorrow. No new PRs will be part of 0.118 after that moment beside bug fixes.
And also your PR needs to be reviewed by the HA team, which can be either done really quickly or can take a couple of weeks as there is a huge backlog of PRs. So don't hold your breath 😉

**Comment by EddyK69** [comment]
@gerard33 Thanx for your review! Fixed some code and commented on your comments 👍

**Comment by EddyK69** [comment]
Closing this one; will create a new one when finishing new sensors instead of attributes.
