### ISSUE TITLE
vehicle_status.py position no longer works

### ISSUE THREAD

**Issue by luka6000** [bimmerconnected/bimmer_connected#261]
**Describe the issue**
HASS is showing this in the logs during startup

WARNING (MainThread) [bimmer_connected.vehicle_status] Vehicle tracking is disabled
and vehicle location is not working
device_tracker entity is not updated with gps location

**Expected behavior**

device_tracker entity is updated with gps location

**Home Assistant version (if used)**

Which Home Assistant version are you using?
2021.1.1
And did it work on a previous version, if so what was the last working version?
2020.12.2
**Your config.yaml**
this is no longer relevant, right?

```yaml
bmw_connected_drive:
  name_of_car:
    username: USERNAME_BMW_CONNECTED_DRIVE
    password: PASSWORD_BMW_CONNECTED_DRIVE
    region: one of "north_america", "china" , "rest_of_world"
````

**Number of cars**
1
If you have more than 1 car please mention that here.
- [ ] I have 2 or more cars linked to the ConnectedDrive account.
- [ ] I have a Mini vehicle linked to my account.

**Output of bimmer_connected fingerprint**

If you have run the [bimmer_connected fingerprint](https://github.com/bimmerconnected/bimmer_connected#data-contributions) please share that data here

*NOTE: It might take us a while to respond on GitHub (we only maintain this in our free time), but we will respond.*

this is the partial output from bimmerconnected status

    "position": {
        "lat": xx.xxxxx,
        "lon": xx.xxxxx,
        "heading": 56,
        "status": "LAST_KNOWN"
    },

and the class that checks for enabled tracking is like this (from vehicle_status.py)
    def is_vehicle_tracking_enabled(self) -> bool:
        """Check if the position tracking of the vehicle is enabled.
        The server return "OK" if tracking is enabled and "DRIVER_DISABLED" if it is disabled in the vehicle.
        """
        return self._state.attributes[SERVICE_STATUS]['position']['status'] == 'OK'

It looks like this is no longer true for rest_of_the_world region.

**Comment by luka6000** [comment]
changed it to 
return ( self._state.attributes[SERVICE_STATUS]['position']['status'] == 'OK' or self._state.attributes[SERVICE_STATUS]['position']['status'] == 'LAST_KNOWN' )

and position in HA works again.

**Comment by luka6000** [comment]
my fingerprint data
[STATUS_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/5793646/STATUS_0.txt)
[vehicles_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/5793647/vehicles_0.txt)

**Comment by rikroe** [comment]
Thanks for the report! I'll adjust it and create a PR to HA this evening!

**Comment by luka6000** [comment]
fixed as suggested for TOO_FAR_AWAY
['position']['status'] not in ['DRIVER_DISABLED', 'TOO_FAR_AWAY']
