### ISSUE TITLE
BMW Connected Drive Component reports „KeyError: 'driveTrain'“

### ISSUE THREAD

**Issue by ruycostajr** [bimmerconnected/bimmer_connected#282]
**Describe the issue**
Home Assistant 0.105.5 integrated 0.70.0 to address an API change at BMW. However, the integration still fails to connect:

**Expected behavior**
Connect to BMW connected drive services and offer car data and actions in Home Assistant.

**Home Assistant version**
Currently: 0.105.5

**Screenshots**
No screenshots taken

**Your config.yaml**

bmw_connected_drive:
  mycar:
    username: !secret bmw_connected_drive_username
    password: !secret bmw_connected_drive_password
    region: "rest_of_world"

**ConnectedDrive website**
- [X ] I can still successfully login to the BMW ConnectedDrive website and the car status is available there.
- [ X] I have ConnectedDrive enabled for my vehicle.

**Number of cars**
Only one - BMW X1 25xdrive 2018 (AWD)
(I have other account integrated with BMW M2 Competition RWD work perfect)

**Output of bimmer_connected fingerprint**
DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:bimmer_connected.account:getting new oauth token
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): customer.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://customer.bmwgroup.com:443 "POST /gcdm/oauth/token HTTP/1.1" 200 None
DEBUG:bimmer_connected.account:got new token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx with expiration date 2021-05-15 20:20:40.746271
DEBUG:bimmer_connected.account:Old token is still valid. Not getting a new one.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): b2vapi.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://b2vapi.bmwgroup.com:443 "GET /webapi/v1/user/vehicles HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/usr/local/bin/bimmerconnected", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/cli.py", line 240, in main
    args.func(args)
  File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/cli.py", line 116, in fingerprint
    log_responses=time_dir)
  File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/account.py", line 66, in __init__
    self._get_vehicles()
  File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/account.py", line 220, in _get_vehicles
    logfilename='vehicles')
  File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/account.py", line 159, in send_request
    self._log_response_to_file(response, logfilename)
  File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/account.py", line 176, in _log_response_to_file
    with open(output_path, 'w') as logfile:
TypeError: invalid file: PosixPath('/root/vehicle_fingerprint/2021-05-15_19-20-39/vehicles_0.txt')

**Output of bimmer_connected status**
DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:bimmer_connected.account:getting new oauth token
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): customer.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://customer.bmwgroup.com:443 "POST /gcdm/oauth/token HTTP/1.1" 200 None
DEBUG:bimmer_connected.account:got new token xxxxxxxxxxxxxxxxxxxxxxx with expiration date 2021-05-15 20:14:50.195573
DEBUG:bimmer_connected.account:Old token is still valid. Not getting a new one.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): b2vapi.bmwgroup.com:443
DEBUG:urllib3.connectionpool:https://b2vapi.bmwgroup.com:443 "GET /webapi/v1/user/vehicles HTTP/1.1" 200 None
DEBUG:bimmer_connected.state:requesting new data from connected drive
Traceback (most recent call last):
  File "/usr/local/bin/bimmerconnected", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/cli.py", line 240, in main
    args.func(args)
  File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/cli.py", line 95, in get_status
    account.update_vehicle_states()
  File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/account.py", line 243, in update_vehicle_states
    car.update_state()
  File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/vehicle.py", line 79, in update_state
    self.state.update_data()
  File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/state.py", line 97, in update_data
    for service in self._vehicle.available_state_services:
  File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/vehicle.py", line 205, in available_state_services
    if self.drive_train != DriveTrainType.CONVENTIONAL:
  File "/usr/local/lib/python3.5/dist-packages/bimmer_connected/vehicle.py", line 84, in drive_train
    return DriveTrainType(self.attributes['driveTrain'])
KeyError: 'driveTrain'

**Comment by rikroe** [comment]
Even though the latest version is 0.7.15 by now, there were no changes to that specific part of code.
Can you please try downloading bimmer_connected through PyPI (0.7.0, 0.7.15 or both) and try running the fingerprint from your user?

Unfortunately the fingerprint files are trying to be stored in a directory that doesn't exist (that was at least partly fixed in a later version).

You could also try editing your [`/usr/local/lib/python3.5/dist-packages/bimmer_connected/cli.py#L13`](https://github.com/bimmerconnected/bimmer_connected/blob/0.6.2/bimmer_connected/cli.py#L13) and replace `os.path.dirname(os.path.abspath(__file__))` with `/tmp` (or any other directory that is available).

**Comment by ruycostajr** [comment]
Hi, 
The tests I did was done on my linux machine, using the version 0.7.15 installed with pip3 install --upgrade bimmer_connected

#pip freeze |grep bimmer
bimmer-connected==0.7.15

When executing the command
#bimmerconnected fingerprint <username> <password> <region>
The directory is created automatically, but does not contain any files.

**Comment by rikroe** [comment]
Are you executing it as root? The path it tries to write (`/root/vehicle_fingerprint/2021-05-15_19-20-39/vehicles_0.txt`) to looks like that at least.

Could you please try to adjust the Python code as in my last reply to store it to `/tmp`?

**Comment by ruycostajr** [comment]
Hi,
Yes, I'm running as root.
In the last version 0.7.15 line 13 that you went through to modify it is different.
