### ISSUE TITLE
Login issue in Home Assistant v2021.8.8, region China

### ISSUE THREAD

**Issue by nichwang88** [bimmerconnected/bimmer_connected#313]
### Describe the issue

The last available version I can login in China was core-2021.8.4, after then I can't login any more, core-2021.8.8 still didn't fix login issue.

### Expected behavior

Fix login issue for "china".

### Which Home Assistant version are you using?

core-2021.8.8

### What was the last working version of Home Assistant Core?

core-2021.8.4

### What is your region?

China

### ConnectedDrive website

- [x] I can still successfully login to the BMW ConnectedDrive website and the car status is available there.
- [X] I have ConnectedDrive enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the ConnectedDrive account.
- [ ] I have a Mini vehicle linked to my account.

### Anything in the logs that might be useful for us?

```txt
Logger: bimmer_connected.account
Source: /usr/local/lib/python3.9/site-packages/bimmer_connected/account.py:168
First occurred: 12:06:27 (3 occurrences) 
Last logged: 12:08:14

Authentication failed (invalid_client): Client authentication failed (unknown client)
```

**Comment by rikroe** [comment]
Thanks for bringing this up! I thought I have accomodated for the old login that still works in `china`.
I'll double check in detail this evening.

**Comment by nichwang88** [comment]
It seems to have some bugs in Version 0.7.20. 
In this version I can login in China, but `sensor.x3_xdrive30i_mileage` `sensor.x3_xdrive30i_remaining_fuel` `sensor.x3_xdrive30i_remaining_range_fuel` `sensor.x3_xdrive30i_remaining_range_total` these value were `unkown`, others worked fine.
Version 0.7.16 worked fine.

**Comment by rikroe** [comment]
Could you maybe provide a `fingerprint` from both 0.7.16 and 0.7.20?

**Comment by nichwang88** [comment]
Sorry, I don't know how to get a fingerprint, I'm using Home Assistant OS 6.2.

**Comment by gerard33** [comment]
@nichwang88 you can use the SSH & Web Terminal addon to get the fingerprint data easily. If you don't have it installed already you can find it in the Add-on Store page of the Supervisor as part of the Home Assistant Community Add-ons.

More info here -> https://github.com/hassio-addons/addon-ssh. I think you need to deactivate the protection mode, at least that is what I have done.

Then go to the terminal (OPEN WEB UI button of the addon) and enter
`pip3 install --upgrade bimmer_connected`

After that you can enter
`bimmerconnected fingerprint <username> <password> china`

It will make a fingerprint with data and store it in `/root/vehicle_fingerprint/<date>_<time>`
You can share the content of the files in that dir here, all sensitive data such as coordinates and VIN are automatically replaced with dummy data but please doublecheck.

**Comment by gerard33** [comment]
Have you disabled protection mode in the settings of the addon?

**Comment by nichwang88** [comment]
@gerard33 Yes, I‘ve disabled protection mode in Portainer, however the SSH & Web Terminal addon didn‘t have this option.

**Comment by gerard33** [comment]
Looks like you are using Terminal & SSH addon and not the SSH & Web Terminal addon. Those are 2 different addons.

The addon you should use looks like this
![image](https://user-images.githubusercontent.com/11230573/131796629-f80d40fa-ecc3-40be-9753-02c260dc4656.png)

And below that are 5 configuration options where the last one is the option for disabling the protection mode.

**Comment by nichwang88** [comment]
@gerard33 Thank you very much. I've install another addon that can't disabling the protection mode.
Now I can run the `pip3 install --upgrade bimmer_connected` and try to find out the `fingerprint` later.

**Comment by nichwang88** [comment]
@gerard33 
I try your custom component
[https://github.com/bimmerconnected/ha_custom_component/tree/master/custom_components/bmw_connected_drive](url)
and it works good!!!
I didn't know what mistake I made, while i `Fork` your ha_custom_component to [https://github.com/nichwang88/ha_custom_component](url)
and I tried to test v0.7.16 and v0.7.20 before HA 2021.9, then you could see `unknow` above.
I will continue test it after update to HA 2021.9.
Really appreciate for your great help!

**Comment by gerard33** [comment]
Good to see it's working again.
I will close this issue. If there is anything else, feel free to re-open it again.
