### ISSUE TITLE
BMW Connected Drive reports wrong remaining_range_total

### ISSUE THREAD

**Issue by astrandb** [bimmerconnected/bimmer_connected#317]
### Describe the issue

BMW Connected reports wrong remaining range for my BMW 330e xDrive.
E.g. today's figures in the car and in myBMW app are: remaining electric range 59 km, remaining total range 573 km.
The integration reports electric range: 59 km; fuel range: 573 km ; total range: 632.
This is nothing new, it has been like this since i got the car last year.

Related to https://github.com/home-assistant/core/issues/54538

### Expected behavior

As shown by the car and by the BMW app:
```
remaining range electric: 59
remaining range fuel: 514 (573-59)
remaining range total: 573
```

### Which Home Assistant version are you using?

core-2021.9

### What is your region?

Rest of world

### ConnectedDrive website

- [X] I can still successfully login to the BMW ConnectedDrive website and the car status is available there.
- [X] I have ConnectedDrive enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the ConnectedDrive account.
- [ ] I have a Mini vehicle linked to my account.

### Output of bimmer_connected fingerprint

```txt
"chargingStatus": "FINISHED_FULLY_CHARGED",
    "checkControlMessages": [],
    "connectionStatus": "CONNECTED",
    "doorDriverFront": "CLOSED",
    "doorDriverRear": "CLOSED",
    "doorLockState": "SECURED",
    "doorPassengerFront": "CLOSED",
    "doorPassengerRear": "CLOSED",
    "fuelPercent": 99,
    "hood": "CLOSED",
    "internalDataTimeUTC": "2021-08-11T21:37:50",
    "lastChargingEndReason": "CHARGING_GOAL_REACHED",
    "lastChargingEndResult": "SUCCESS",
    "mileage": 20850,
    "position": {
      "heading": 123,
      "lat": 12.3456,
      "lon": 34.5678,
      "status": "OK"
    },
    "rearWindow": "CLOSED",
    "remainingFuel": 35,
    "remainingRangeElectric": 59,
    "remainingRangeElectricMls": 36,
    "remainingRangeFuel": 573,
    "remainingRangeFuelMls": 356,
    "singleImmediateCharging": false,
    "trunk": "CLOSED",
    "updateReason": "DOOR_STATE_CHANGED",
    "updateTime": "2021-08-11T21:37:50+0000",
    "vehicleCountry": "SE",
    "vin": "some_vin",
    "windowDriverFront": "CLOSED",
    "windowDriverRear": "CLOSED",
    "windowPassengerFront": "CLOSED",
    "windowPassengerRear": "CLOSED"
```

### Additional information

Screen shots from the app: https://github.com/home-assistant/core/issues/54538

**Comment by robthebold** [comment]
So it's effectively adding the electric range twice to the total, right?

**Comment by gerard33** [comment]
@robthebold so for your car the ranges shown in HA are the same as shown in myBMW app?

We are looking into using new BMW endpoints, maybe those give more data related to this for newer cars.
