### ISSUE TITLE
0.8.0 Missing max range

### ISSUE THREAD

**Issue by nottledim** [bimmerconnected/bimmer_connected#349]
### Describe the issue

The attribute bmw_max_range aka max_range_electric in cli has a null value.

BMW i3 120

### Expected behavior

It always used to show max_range 

### Which Home Assistant version are you using?

core 2021.11.4

### What is your region?

Rest of world

### ConnectedDrive website

- [X] I can still successfully login to the BMW ConnectedDrive website and the car status is available there.
- [X] I have ConnectedDrive enabled for my vehicle.

### Number of cars

- [X] I have 2 or more cars linked to the ConnectedDrive account.
- [ ] I have a Mini vehicle linked to my account.

**Comment by nottledim** [comment]
bmw_max range is local to me; it's template that converts sensor.i3_120_max_range_electric from km to miles.  
Sorry if I confused you.

**Comment by rikroe** [comment]
Are you using the custom component from https://github.com/bimmerconnected/ha_custom_component?
If yes, please provide a fingerprint and check if you can find a matching value. I think it is not available anymore.

If not using the custom component, you have to wait for a HA update or use the custom component until then as BMW changed their API.

**Comment by nottledim** [comment]
Yes, custom component.  fingerprints is a new thing to me.  I can't see anything that looks like max-range in the json output. I'm not bothered if it's not there it's just I noticed.


[vehicles_v2_bmw_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/7566598/vehicles_v2_bmw_0.txt)

**Comment by rikroe** [comment]
Then it is unfortunately not support by the new API anymore.
