### ISSUE TITLE
All BWM Entity disappeared

### ISSUE THREAD

**Issue by giugit** [bimmerconnected/bimmer_connected#351]
### Describe the issue

I delete the integration and i'm trying to install it again, when i have to choose China north_america or rest of the world, i'm in Italy so i select rest of the world but the password that work on the web site https://www.bmw.it/it/shop/ls/cp/connected-drive are not recognised!
How can I reinstall the integration?
Thanks

### Expected behavior

The password would be recognised

### Which Home Assistant version are you using?

core-2021.11.4

### What is your region?

Rest of world

### ConnectedDrive website

- [X] I can still successfully login to the BMW ConnectedDrive website and the car status is available there.
- [X] I have ConnectedDrive enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the ConnectedDrive account.
- [ ] I have a Mini vehicle linked to my account.

**Comment by rikroe** [comment]
There is an issue with login in HA. You have to wait for our fixes being included in HA or use the custom component for now: https://github.com/bimmerconnected/ha_custom_component

**Comment by rikroe** [comment]
Closing as it was fixed within the library/custom component and is included in the HA 2021.12 beta, so it will be released in HA on Dec. 11th.
