### ISSUE TITLE
ValueError: Either latitude and longitude are both not None or both are None.

### ISSUE THREAD

**Issue by licheng5625** [bimmerconnected/bimmer_connected#371]
### Describe the issue

When I try to create a fingure print for mini phev 2019. I got following error 

DEBUG:urllib3.connectionpool:https://cocoapi.bmwgroup.com:443 "GET /eadrax-vcs/v1/vehicles?apptimezone=60.0&appDateTime=1638288735.940279&tireGuardMode=ENABLED HTTP/1.1" 200 8269
Traceback (most recent call last):
  File "/usr/local/bin/bimmerconnected", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/cli.py", line 282, in main
    args.func(args)
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/cli.py", line 128, in fingerprint
    account.set_observer_position(args.lat, args.lng)
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 434, in set_observer_position
    raise ValueError('Either latitude and longitude are both not None or both are None.')
ValueError: Either latitude and longitude are both not None or both are None.

### Expected behavior

getting figure print

### Which Home Assistant version are you using?

none 

### What is your region?

Rest of world

### ConnectedDrive website

- [X] I can still successfully login to the BMW ConnectedDrive website and the car status is available there.
- [X] I have ConnectedDrive enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the ConnectedDrive account.
- [X] I have a Mini vehicle linked to my account.

### Output of bimmer_connected fingerprint

```txt
None
```

**Comment by rikroe** [comment]
You'll need to supply the command line parameters `lat` and `lon` for now (can be 0.0 and 0.0).
I'll introduce a switch into the cli.

For more information for now please check the docs: https://bimmer-connected.readthedocs.io/en/latest/cli.html#fingerprint
