### ISSUE TITLE
BMW connected Drive BETA can not be found in configuration, integration

### ISSUE THREAD

**Issue by mjxoicq** [bimmerconnected/bimmer_connected#388]
I have successfully downloaded 'BMW connected Drive BETA' repository in HACS, but I can not find it when I try to add integration in configuration. I can only find the official BMW connected Drive, which always say 'Failed to connect'.

Here are some logs after I restart Home Assistant, I am not sure whether it is helpful for you to find the problem:

[Log 1]
Logger: bimmer_connected.account
Source: /usr/local/lib/python3.9/site-packages/bimmer_connected/account.py:261
First occurred: 24:42:16 (2 occurrences)
Last logged: 24:54:47

Authentication failed (True): 系统异常，请稍后再试！( It means 'System Error, please try again later')

[Log 2]
Logger: bimmer_connected.account
Source: /usr/local/lib/python3.9/site-packages/bimmer_connected/account.py:107
First occurred: 24:42:16 (2 occurrences)
Last logged: 24:54:47

422 Client Error: Unprocessable Entity for url: https://myprofile.bmw.com.cn/eadrax-coas/v1/login/pwd
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 96, in _get_oauth_token
    token_data = self._login_china()
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 264, in _login_china
    raise ex
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 245, in _login_china
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://myprofile.bmw.com.cn/eadrax-coas/v1/login/pwd

Looking forward to your reply, thanks a lot!

**Comment by mjxoicq** [comment]
Thanks! I did not know 86 is needed. Now the official integration works!

**Comment by rikroe** [comment]
I'll update the Home Assistant documentation for this.

**Comment by rikroe** [comment]
Will be fixed with the documentation of HomeAssistant 2022.04.
