### ISSUE TITLE
sensor.cooper_s_e_all4_remaining_range_electric is not availble when car is not charged

### ISSUE THREAD

**Issue by licheng5625** [bimmerconnected/bimmer_connected#389]
### Describe the issue

Hi, wish you and your family have a happy xmas and new year
sensor.cooper_s_e_all4_remaining_range_electric sensor shows as not availble when car is not charged.
In app it shows as "--", it just means 0.
 {
          "barType": null,
          "chargingStatusIndicatorType": "DEFAULT",
          "chargingStatusType": "DEFAULT",
          "chargingType": null,
          "iconOpacity": "high",
          "infoIconId": 59694,
          "infoLabel": "State of Charge",
          "isCircleIcon": false,
          "isInaccurate": false,
          "levelIconId": 59694,
          "levelUnits": "%",
          "levelValue": "9",
          "mainBarValue": 9,
          "rangeIconId": 59683,
          "rangeUnits": "km",
          "rangeValue": "- -",
          "secondaryBarValue": 0,
          "showBarGoal": false,
          "showsBar": true
        },

### Expected behavior

show as 0 km

### Which Home Assistant version are you using?

core-2021.12.4

### What is your region?

Rest of world

### ConnectedDrive website

- [X] I can still successfully login to the BMW ConnectedDrive website and the car status is available there.
- [ ] I have ConnectedDrive enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the ConnectedDrive account.
- [X] I have a Mini vehicle linked to my account.

### Output of bimmer_connected fingerprint

```txt
{
          "barType": null,
          "chargingStatusIndicatorType": "DEFAULT",
          "chargingStatusType": "DEFAULT",
          "chargingType": null,
          "iconOpacity": "high",
          "infoIconId": 59694,
          "infoLabel": "State of Charge",
          "isCircleIcon": false,
          "isInaccurate": false,
          "levelIconId": 59694,
          "levelUnits": "%",
          "levelValue": "9",
          "mainBarValue": 9,
          "rangeIconId": 59683,
          "rangeUnits": "km",
          "rangeValue": "- -",
          "secondaryBarValue": 0,
          "showBarGoal": false,
          "showsBar": true
        },
```
```


### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

**Comment by rikroe** [comment]
Thanks, hope you had great holidays with your family as well!
From what I can see in other provided fingerprints, `- -` rather means _"BMW cannot calculate a remaining range"._ 

- in your case, there is unknown remaining electric range with 9% charge
- in the [F31 fingerprint](https://github.com/bimmerconnected/bimmer_connected/blob/master/test/responses/F31/vehicles_v2_bmw_0.json#L212-L229), there is unknown remaining fuel range with 32 L of fuel
- in the [F11 fingerprint](https://github.com/bimmerconnected/bimmer_connected/blob/master/test/responses/F11/vehicles_v2_bmw_0.json#L218-L235), there is unknown remaining fuel range with 24 L of fuel 

Therefore, having a `0` output doesn't seem right to me, even if BMW is providing "incorrect" values.
