### ISSUE TITLE
A suggestion: add the 'state_class' property for the fuel and mileage entities to use the 'statistic' function in HA

### ISSUE THREAD

**Issue by muxiachuixue** [bimmerconnected/bimmer_connected#398]
### Describe the issue

The question:
The historical data of the car in HA only applies to the past 10 days for default. If you want to analyse the fuel consumption for past several months, you can only set the parameter `keep_days` in [recorder](https://www.home-assistant.io/integrations/recorder) to a larger value which will impact all the entities in HA and increase the size of the database file.

The solution:
According to the [official instruction of HA](https://www.home-assistant.io/more-info/statistics/), if a sensor entity contains the `state_class` property and the value is `measurement`, the statistic function will be available. So it will be useful if the `state_class` property is added to the mileage/fuel_percent/remaining_range entities.

Looking forward to see the update. Many thanks for your great work!

### Expected behavior

Add the `state_class` property for the fuel and mileage entities to use the 'statistic' function in HA

### Which Home Assistant version are you using?

core-2021.12.7

### What is your region?

China

### ConnectedDrive website

- [X] I can still successfully login to the BMW ConnectedDrive website and the car status is available there.
- [X] I have ConnectedDrive enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the ConnectedDrive account.
- [ ] I have a Mini vehicle linked to my account.

**Comment by rikroe** [comment]
Thanks, good idea! I'll have a look into this.
