### ISSUE TITLE
China: Login requires captcha

### ISSUE THREAD

**Issue by rikroe** [bimmerconnected/bimmer_connected#416]
![Screenshot_2022-01-16-20-01-56-99_2769d0ca37355d194b0fe3f4241b60fe](https://user-images.githubusercontent.com/29619015/149659227-5eee2a6a-f5a0-43c9-9d35-6ad38c5d195b.jpg)

_Originally posted by @ouhaiorg in https://github.com/bimmerconnected/bimmer_connected/discussions/415#discussioncomment-1977715_

**Comment by rikroe** [comment]
It seems that before sending the login, a captcha check is done by posting to `https://myprofile.bmw.com.cn/eadrax-coas/v2/cop/is-captcha-needed` (usual headers) with content `{"mobile": "86xxxxxxxx"}`. 
In my case (a test account without vehicles), I just get the following return value (`"data": false` probably meaning no captcha needed).
```json
{
    "data": false,
    "code": 200,
    "error": false,
    "description": "ok"
}
```

@muxiachuixue have you seen this as well? You know of a way not to require a captcha?

**Comment by muxiachuixue** [comment]
> 

This is because the user has entered the wrong password for too many times. Try to open MyBMW app to logout and login again. Then this error will disappear.

**Comment by ouhaiorg** [comment]
curl -d 'mobile=86139********' https://myprofile.bmw.com.cn/eadrax-coas/v2/cop/is-captcha-needed, the output is:
{"data":false,"code":200,"error":false,"description":"ok"}
but  when I use any mobile number,the output as the same.

**Comment by ouhaiorg** [comment]
after 2022/1/12，bimmer_connected authentication failed.
![IMG_20220117_113709](https://user-images.githubusercontent.com/29619015/149711555-8375ab52-bc6e-40d9-bd81-7c471b945de3.jpg)

**Comment by ouhaiorg** [comment]
Thanks, now the bimmer_connected work fine, but MyBMW app login in requires captcha.

**Comment by rikroe** [comment]
Closed per https://github.com/bimmerconnected/bimmer_connected/discussions/415#discussioncomment-1980186
