### ISSUE TITLE
In China, the location of the car shifts in HA when the device_tracker.xxx is updated

### ISSUE THREAD

**Issue by muxiachuixue** [bimmerconnected/bimmer_connected#419]
### Describe the issue

When I restart HA or execute the following service, the gps location of the car in HA will shift to northwest:
```
service: homeassistant.update_entity
target:
  entity_id:
    - device_tracker.my_car
```
In [#378](https://github.com/bimmerconnected/bimmer_connected/pull/378), you fixed the coordinates shift. However, when the entity is updated, it seems that the conversion algorithm is executed again. If the `homeassistant.update_entity` service is called for 10 times, the coordinates of the car will shift 10 times far away from the correct location.

### Expected behavior

When `device_tracker.my_car` is updated in HA, the location of the car will not shift.

### Which Home Assistant version are you using?

core-2022.2.6

### What is your region?

China

### ConnectedDrive website

- [X] I can still successfully login to the BMW ConnectedDrive website and the car status is available there.
- [X] I have ConnectedDrive enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the ConnectedDrive account.
- [ ] I have a Mini vehicle linked to my account.

**Comment by rikroe** [comment]
Thanks for the report, the fix is easy but was also easy to miss (see #421).

**Comment by muxiachuixue** [comment]
> Thanks for the report, the fix is easy but was also easy to miss (see #421).

Thanks. So when this new update will be available for HA? The 2022.3.0 version of HA has just been released, but I did not see the update of `BMW Connected Drive`.

**Comment by rikroe** [comment]
It is included, but only visible in the full changelog at https://www.home-assistant.io/changelogs/core-2022.2

Seems they had to split it off otherwise it would have been too long.

**Comment by muxiachuixue** [comment]
> It is included, but only visible in the full changelog at https://www.home-assistant.io/changelogs/core-2022.2
> 
> Seems they had to split it off otherwise it would have been too long.

Then this is strange. When I call the following service, the location of the car still shift in the official map of HA.
```
service: homeassistant.update_entity
target:
  entity_id:
    - device_tracker.my_car
```


My HA version information:  

## System Health

version | core-2022.2.9
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.60-v7l+
arch | armv7l
timezone | Asia/Shanghai

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | failed to load: unreachable
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.23.0
Stage | running
Available Repositories | 1066
Downloaded Repositories | 22

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Raspbian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.8
disk_total | 58.2 GB
disk_used | 17.2 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Node-RED (10.2.0), Terminal & SSH (9.3.0), Portainer (2.0.0), AirSonos (3.2.0), Let's Encrypt (4.12.0), NGINX Home Assistant SSL proxy (3.1.1), Nginx Proxy Manager (0.11.0), ZeroTier One (0.12.2), AdGuard Home (4.4.2), InfluxDB (4.3.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 16
views | 4
mode | storage

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.5.3
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 30

</details>
