### ISSUE TITLE
Can not lock the car after new update 20220327.1

### ISSUE THREAD

**Issue by dharvey242** [bimmerconnected/bimmer_connected#425]
### Describe the issue

I have just updated to 20220327.1 and now I can see all the status updates but am unable to lock/unlock car.  

### Expected behavior

To be able to click lock/unlock remotely through Home Assistant. 

### Which Home Assistant version are you using?

core-2022.3.7

### What is your region?

Rest of world

### ConnectedDrive website

- [X] I can still successfully login to the BMW ConnectedDrive website and the car status is available there.
- [X] I have ConnectedDrive enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the ConnectedDrive account.
- [ ] I have a Mini vehicle linked to my account.

**Comment by rikroe** [comment]
Can you please try again and provide the log from Homeassistant?

**Comment by dharvey242** [comment]
Thanks for looking at this.
I can't try as the entity option is greyed out.  The state is correct.  But previously I could click on lock or unlock and it would work.

**Comment by dharvey242** [comment]
For example

![image](https://user-images.githubusercontent.com/56608124/160597631-84b2afec-934f-4dd9-878c-87a3a91925c4.png)

**Comment by rikroe** [comment]
What's your car's model year? This happens on older cars that don't show the current lock state.

Can you open the detail screen for the lock (clicking on the lock icon)? There should be lock & unlock and it should work there.

**Comment by dharvey242** [comment]
Okay thanks that worked and now the option has returned to lock and unlock via the main screen.  I guess it can't get the state until its told to go and look.  odd how it worked before.  Anyhow solved. Kinda.  Many thanks.

![image](https://user-images.githubusercontent.com/56608124/160603081-f2372848-6615-418d-b35e-32265f39a1fd.png)

**Comment by rikroe** [comment]
I'll close this issue now, if it comes up again (e.g. after HA restart) please let me know. 
Maybe there is something we can/have to do on the component side.

**Comment by dharvey242** [comment]
Yep after a restart it remains.  Not a major problem.  Just needs an additional click.

**Comment by rikroe** [comment]
Lock state should be fixed with [20220331.1](https://github.com/bimmerconnected/ha_custom_component/releases/tag/20220331.1).

**Comment by dharvey242** [comment]
Confirmed as working.  Thanks.
