### ISSUE TITLE
What is the use for 'available_attributes' or 'drive_train_attributes'

### ISSUE THREAD

**Issue by FlyingDiver** [bimmerconnected/bimmer_connected#438]
### Describe the issue

Based on the API description, I would expect the list of attributes to be retrievable using something like:
```

            for attrib in vehicle.available_attributes:
                self.logger.debug(f"Looking for {attrib}")
                self.logger.debug(f"{attrib}: ({getattr(vehicle, attrib)}")
```

But when I do that I get:
```
Looking for gps_position
...
type: 'MyBMWVehicle' object has no attribute 'gps_position'
```

### Expected behavior

I expected that the Vehicle object would actually have the attributes listed.

### Which Home Assistant version are you using?

None

### What is your region?

North America

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

**Comment by rikroe** [comment]
Good catch, pulling out all the legacy stuff.

Before the rewrite, the vehicle's `__getattr__` was overwritten ([see here](https://github.com/bimmerconnected/bimmer_connected/blob/3d71a535abebb8aed74eb4346426ae7edd025d90/bimmer_connected/vehicle.py#L219-L229)) to also check the attributes of `VehicleStatus` (where `gps_location` was to be found).
With the rewrite, this is not as easy as there are now multiple attributes that store detailed data (e.g. `location`, `doors_and_windows`, ...).

The main idea behind `available_attributes` was to enable Home Assistant to show only sensors/attributes available on your car. However this was never done automagically, but always hardcoded (e.g. https://github.com/home-assistant/core/blob/dev/homeassistant/components/bmw_connected_drive/sensor.py).

I don't really know what to do with those attributes. For Home Assistant we need to distinguish between very old cars (pre mid-2014) and newer and if they have an internal combustion engine, electric motor or both.

If you have any suggestions, I'd be absolutely open!

**Comment by FlyingDiver** [comment]
Since I'm not using Home Assistant, it doesn't matter to me.  I'll just ignore those methods.

**Comment by rikroe** [comment]
In that case, yes, that is perfectly fine.
