### ISSUE TITLE
SECURED LockState no longer available

### ISSUE THREAD

**Issue by turribeach** [bimmerconnected/bimmer_connected#442]
### Describe the issue

Hi,

I used to be able to see the LockState as SECURED when the doors were locked and the alarm was activated:

https://bimmer-connected.readthedocs.io/en/latest/module/vehicle.html#bimmer_connected.vehicle.doors_windows.LockState

But now it seems to be set to LOCKED instead of SECURED. 

### Expected behavior

 LockState set as SECURED when the doors were locked and the alarm was activated

### Which Home Assistant version are you using?

Not using HA

### What was the last working version of Home Assistant Core?

Not using HA

### What is your region?

Rest of world

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

**Comment by rikroe** [comment]
There wasn't any change how the API values are parsed, so I guess there was a change in the BMW side.

Please provide a fingerprint using `bimmerconnected fingerprint` when the vehicle should provide the `SECURED` value so we can check against the provided values.

**Comment by turribeach** [comment]
Hi, thanks for the reply. I have checked the fingerprint values in both cases with the car "locked" and the car "secured" and it always comes as "locked" so I think you are right, they must have changed it at their side. It's a pitty really as this was very handy. I also just started to get 403 Forbidden on my calls. Not sure if I polled it too quickly (every 5mins) and they banned me or something...

**Comment by FlyingDiver** [comment]
You're not the only one getting 403:  https://github.com/bimmerconnected/bimmer_connected/discussions/443

**Comment by mibo-wb-gh** [comment]
> You're not the only one getting 403: #443

Same here. logs tells me
403 Client Error: Forbidden for url: https://cocoapi.bmwgroup.com/eadrax-ucs/v1/presentation/oauth/config

or

Error fetching bmw_connected_drive-"email address" data: Error communicating with API: 429 Client Error: Too Many Requests for url: https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles?apptimezone=120.0&appDateTime=......

Then it just starts working again, without changing or restarting anything
Sometimes it helps to restart the integration, and sometimes restarting the integration does not help

Would presume that bmw are working on something or messed something up !

**Comment by turribeach** [comment]
Are you sure it's working at times for you? I have not got a successful update since ~10am BST this morning. BTW I raised this issue now:

https://github.com/bimmerconnected/bimmer_connected/issues/444

So probably best to move the discussion there.

**Comment by mibo-wb-gh** [comment]
> Are you sure it's working at times for you? I have not got a successful update since ~10am BST this morning. BTW I raised this issue now:
> 
> #444
> 
> So probably best to move the discussion there.

It worked for the last time for few minutes this morning at around 11:20 CET, since then the no login has been possible

**Comment by rikroe** [comment]
As BMW seemed to have changed the API (and the 403 error has been fixed since a month), I am closing this.
