### ISSUE TITLE
BMW Connected drive failing on home assistant

### ISSUE THREAD

**Issue by puttemanp** [bimmerconnected/bimmer_connected#446]
### Describe the issue

Since a few days the BMW Connected Drive integration fails. It started with the location of the car not being updated, to entities becoming unavailable. Reloading the integration made the entities available again, except the location of the car.

The integration dashboard shows: Retrying setup: local variable ‘response’ referenced before assignment

### Expected behavior

Enitities available and location of car updated

### Which Home Assistant version are you using?

core-2022.5.5

### What was the last working version of Home Assistant Core?

core-22.5.4

### What is your region?

Rest of world

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

### Anything in the logs that might be useful for us?

```txt
Since a few days the BMW Connected Drive integration fails. It started with the location of the car not being updated, to entities becoming unavailable. Reloading the integration made the entities available again, except the location of the car.

The integration dashboard shows: Retrying setup: local variable ‘response’ referenced before assignment

Lofgfile:

Traceback (most recent call last):
File “/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py”, line 128, in _login_row_na
r_oauth_settings.raise_for_status()
File “/usr/local/lib/python3.9/site-packages/requests/models.py”, line 960, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://cocoapi.bmwgroup.com/eadrax-ucs/v1/presentation/oauth/config
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File “/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py”, line 220, in _login_row_na
err = response.json()
UnboundLocalError: local variable ‘response’ referenced before assignment
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File “/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py”, line 191, in _async_refresh
self.data = await self._async_update_data()
File “/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/coordinator.py”, line 59, in _async_update_data
self.account = await self.hass.async_add_executor_job(
File “/usr/local/lib/python3.9/concurrent/futures/thread.py”, line 58, in run
result = self.fn(*self.args, **self.kwargs)
File “/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py”, line 88, in init
self._get_vehicles()
File “/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py”, line 383, in _get_vehicles
self._get_oauth_token()
File “/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py”, line 113, in _get_oauth_token
raise ex
File “/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py”, line 99, in _get_oauth_token
token_data = self._login_row_na()
File “/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py”, line 223, in _login_row_na
_LOGGER.error(“Authentication failed: %s”, response.text)
UnboundLocalError: local variable ‘response’ referenced before assignment
```

**Comment by davecarlson** [comment]
I am also getting 403 while trying to use the status endpoint via the CLI

**Comment by tonimori** [comment]
same for me.

**Comment by rikroe** [comment]
The issue was raised in https://github.com/bimmerconnected/bimmer_connected/issues/444 and should be resolved soon.
Just want to get another fix in and then create a new release which will be included in HA 2022.6.

**Comment by turribeach** [comment]
If you want this update you will need to wait until a new package release is created before you can upgrade directly with pip. In the meantime you can get the latest code from master branch as follows:

    git clone https://github.com/bimmerconnected/bimmer_connected.git
    cd ./bimmer_connected
    pip install -e .

**Comment by rikroe** [comment]
Yes, however if you're using this in Home Assistant, it will always revert back to the version defined in the component on restart.

**Comment by rikroe** [comment]
You can now use the latest version of the custom component or manually upgrade to 0.9.2 if you are not using HA.
