### ISSUE TITLE
Distances in miles instead of km

### ISSUE THREAD

**Issue by rikroe** [bimmerconnected/bimmer_connected#450]
I just upgraded to the latest verion of the library and now all my data comes back with mi instead of km in the units. How can I change it back to km?

_Originally posted by @th0mi in https://github.com/bimmerconnected/bimmer_connected/discussions/448_

**Comment by rikroe** [comment]
Created an issue to track it better. For more information, see the original discussion.

**Comment by sincze** [comment]
> I just upgraded to the latest verion of the library and now all my data comes back with mi instead of km in the units. How can I change it back to km?
> 
> _Originally posted by @th0mi in #448_

Noticed that as well, please find a work around here.
https://github.com/bimmerconnected/bimmer_connected/discussions/448
