### ISSUE TITLE
Login error in China

### ISSUE THREAD

**Issue by muxiachuixue** [bimmerconnected/bimmer_connected#452]
### Describe the issue

The login failed from yesterday. The Siri Shortcuts work well. So the problem may not come from the BMW APIs.
The BMW Connected Drive BETA version is `20220529.1`. Restart did not work.
 
```
Logger: bimmer_connected.api.authentication
Source: /usr/local/lib/python3.9/site-packages/bimmer_connected/api/utils.py:50
First occurred: 08:32:27 (4 occurrences)
Last logged: 08:33:11

Authentication error: {"data":null,"code":499200,"error":true,"msgType":"toast","description":"非法的登录请求！"}
```

```
Logger: homeassistant.config_entries
Source: config_entries.py:366
First occurred: 08:32:27 (1 occurrences)
Last logged: 08:32:27

Config entry 'BMW' for bmw_connected_drive integration not ready yet: Error communicating with BMW API: Client error '422 Unprocessable Entity' for url 'https://myprofile.bmw.com.cn/eadrax-coas/v2/login/pwd' For more information check: https://httpstatuses.com/422; Retrying in background
```

### Expected behavior

Fix the login errors.

### Which Home Assistant version are you using?

core-2022.5.5

### What was the last working version of Home Assistant Core?

core-2022.5.2

### What is your region?

China

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

**Comment by rikroe** [comment]
Before I create a new release, please try the latest changes from the PR.

**Comment by muxiachuixue** [comment]
> ~It's a different error now, at a different URL.~
> 
> Nevermind, it was still the same issue. Don't know why it worked in my testing, shouldn't have worked. With 2.5.0 apparently the `x-login-nonce` calculation was changed again because we had implemented it, therefore login doesn't work. Reverted back to 2.3.0, but no idea how long that will continue to work.
> 
> New login nonce example (definetly doesn't look like the AES-CBC base64 encoded values we've seen before):
> 
> ```
> nzcm9kf0wzbdsanqd910aa86475985024098541fa2fa7f60000eaed56265456ab72b0b368534d21d9fc4cf8c2245f9ef1b134d5aef21b008d59871d5a1903fdf21c021d01611f9e1ccszwxonykgbnkahc3c864804c9ff76323c768731201599a9cfe08b31e2a9e5907ba373af793ae2f
> ```

Yes, they have changed it again. Reverting back to 2.3.0 works. The situation is the same in Siri shortcuts.

**Comment by rikroe** [comment]
If there is a refresh token, that should be used for login. However in ROW, a refresh token can only be used once. Therefore I have implemented a clearing of the refresh token, if login with refresh token fails ([api/authentication.py#L121-L122](https://github.com/bimmerconnected/bimmer_connected/blob/master/bimmer_connected/api/authentication.py#L121-L122)) - doesn't matter if it fails because of an expired token or network issues/whatsoever. 

Can a refresh token be used multiple times in CN? If yes, I'll remove the clearing of the token.

**Comment by muxiachuixue** [comment]
The refresh token can only be used once in CN. However, when the program gets a access token from the API using the refresh token, a new refresh token will also be produced. So you can update the old refresh token with the new one. The latest refresh token can be invalid if the user changes the password or a verification code is required. So I do not understand why the integration called the password login API in my HA. Is that because when the integration is updated to a new version, the previous stored refresh token will be cleared, so the program has to get a new refresh token from the password login API? If that is the truth, you may store the latest refresh token away from the installation path which will not be influenced by the updating of the integration or HA.

**Comment by rikroe** [comment]
If a refresh_token is stored into HA, it will only be removed if the library is not able to provide a new token (i.e. login failed with refresh token or HTTP connection error when getting a refresh token).

That is at least my understanding, don't know if there are edge cases where HA is clearing the token.

I have updated the PR to not clear the refresh_token in case login with it fails (which is also rather the way that the app is working).
