### ISSUE TITLE
mini cannot receive destination sent from Home assistant since 2022.6.x

### ISSUE THREAD

**Issue by licheng5625** [bimmerconnected/bimmer_connected#455]
### Describe the issue

Hi, 
The car cannot receive any destination sent from HASS. The problem began since 2022.6.x, currently I am running 2022.6.5. The problem is still there. 
There is no error messages in the log.

I still can send location from Mini connect App.
Could you have a look?

### Expected behavior

Receive message in the car

### Which Home Assistant version are you using?

2022.6.5

### What was the last working version of Home Assistant Core?

2022.5.x

### What is your region?

Rest of world

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [X] I have a Mini vehicle linked to my account.

### Anything in the logs that might be useful for us?

```txt
Sorry there is no log relavant.
```

**Comment by rikroe** [comment]
Yes, I can confirm the issue. Seems the API needs more data filled (or at least empty fields given) to work. Unfortunately, that will be a bit of a trial and error to figure out.
