### ISSUE TITLE
MILD_HYBRID is not a valid DriveTrainType

### ISSUE THREAD

**Issue by pixel8383** [bimmerconnected/bimmer_connected#464]
### Describe the issue

I am getting the following error:

> Logger: bimmer_connected.models
> Source: /usr/local/share/homeassistant/lib/python3.9/site-packages/bimmer_connected/models.py:23
> 'MILD_HYBRID' is not a valid 'DriveTrainType'

I guess the library is not expecting this kind of powertrain.

### Expected behavior

My BMW is a Diesel mild hybrid (320d G21).

### Which Home Assistant version are you using?

2022.7.0

### What was the last working version of Home Assistant Core?

2022.6.x

### What is your region?

Rest of world

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

**Comment by rikroe** [comment]
Will have a look - for clarification, you can't charge or use any of the plug in hybrid/electric features, right?

Also, was it just a warning (some sensors are still shown) or a hard error?

**Comment by pixel8383** [comment]
Yep, I do confirm: I can't charge my car nor I can use any remote function destined to electric models.

The sensors are shown so it's not an hard error but it appears multiple times in my error log.

**Comment by rikroe** [comment]
Thanks for the clarification!

> The sensors are shown so it's not an hard error but it appears multiple times in my error log.

That is very good! Previously, it would have failed hard (leading to all kinds of issues such as missing data on other sensors), now only the sensors that are depending on the specific value will fail.

**Comment by rikroe** [comment]
While this will be closed when mergin the pull request, it might take until it is available in a new release and then in HA. Please check the release notes of this library and the HA minor versions.
