### ISSUE TITLE
api reports 400 Bad Request when requesting vehicles

### ISSUE THREAD

**Issue by stefan-hausmeister** [bimmerconnected/bimmer_connected#471]
### Describe the issue

Login seems to work, but requesting the vehicles fails with a 400 Bad Request - see fingerprint

client error '400 Bad Request' for url 'https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles?apptimezone=120.0&appDateTime=1657867882563&tireGuardMode=ENABLED'

last time successful request was 2022/07/14 17:00:00 (UTC+2)

### Expected behavior

Receive a list of vehicles instead of an error message

### Which Home Assistant version are you using?

none

### What is your region?

Rest of world

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

### Output of bimmer_connected fingerprint

```txt
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:bimmer_connected.api.authentication:Authenticating with MyBMW flow for North America & Rest of World.
DEBUG:httpx._client:HTTP Request: GET https://cocoapi.bmwgroup.com/eadrax-ucs/v1/presentation/oauth/config "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: POST https://customer.bmwgroup.com/gcdm/oauth/authenticate "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: POST https://customer.bmwgroup.com/gcdm/oauth/authenticate "HTTP/1.1 302 Found"
DEBUG:httpx._client:HTTP Request: POST https://customer.bmwgroup.com/gcdm/oauth/token "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: GET https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles?apptimezone=120.0&appDateTime=1657867882563&tireGuardMode=ENABLED "HTTP/1.1 400 Bad Request"
Traceback (most recent call last):
  File "/home/pi/.local/bin/bimmerconnected", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/bimmer_connected/cli.py", line 263, in main
    loop.run_until_complete(args.func(args))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/.local/lib/python3.7/site-packages/bimmer_connected/cli.py", line 135, in fingerprint
    await account.get_vehicles()
  File "/home/pi/.local/lib/python3.7/site-packages/bimmer_connected/account.py", line 76, in get_vehicles
    for brand in CarBrands
  File "/home/pi/.local/lib/python3.7/site-packages/bimmer_connected/account.py", line 76, in <listcomp>
    for brand in CarBrands
  File "/home/pi/.local/lib/python3.7/site-packages/httpx/_client.py", line 1760, in get
    extensions=extensions,
  File "/home/pi/.local/lib/python3.7/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/pi/.local/lib/python3.7/site-packages/httpx/_client.py", line 1618, in send
    history=[],
  File "/home/pi/.local/lib/python3.7/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    history=history,
  File "/home/pi/.local/lib/python3.7/site-packages/httpx/_client.py", line 1700, in _send_handling_redirects
    raise exc
  File "/home/pi/.local/lib/python3.7/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    await hook(response)
  File "/home/pi/.local/lib/python3.7/site-packages/bimmer_connected/api/client.py", line 64, in raise_for_status_event_handler
    response.raise_for_status()
  File "/home/pi/.local/lib/python3.7/site-packages/httpx/_models.py", line 736, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles?apptimezone=120.0&appDateTime=1657867882563&tireGuardMode=ENABLED'
For more information check: https://httpstatuses.com/400
```

**Comment by stefan-hausmeister** [comment]
Can be closed.
Sorry, updated to the latest version, working again. Only fingerprint serves an error, but service itself is working.

DEBUG:asyncio:Using selector: EpollSelector
DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:bimmer_connected.api.authentication:Authenticating with MyBMW flow for North America & Rest of World.
DEBUG:httpx._client:HTTP Request: GET https://cocoapi.bmwgroup.com/eadrax-ucs/v1/presentation/oauth/config "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: POST https://customer.bmwgroup.com/gcdm/oauth/authenticate "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: POST https://customer.bmwgroup.com/gcdm/oauth/authenticate "HTTP/1.1 302 Found"
DEBUG:httpx._client:HTTP Request: POST https://customer.bmwgroup.com/gcdm/oauth/token "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: GET https://cocoapi.bmwgroup.com/eadrax-vcs/v2/vehicles "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: GET https://cocoapi.bmwgroup.com/eadrax-vcs/v2/vehicles "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: GET https://cocoapi.bmwgroup.com/eadrax-vcs/v2/vehicles/WBY1Z21030V792005/state "HTTP/1.1 200 OK"
DEBUG:httpx._client:HTTP Request: GET https://cocoapi.bmwgroup.com/eadrax-crccs/v1/vehicles/WBY1Z21030V792005?fields=charging-profile&has_charging_settings_capabilities=true "HTTP/1.1 500 Internal Server Error"
fingerprint of the vehicles written to /home/pi/vehicle_fingerprint/2022-07-15_09-04-58

**Comment by rikroe** [comment]
The fingerprint error is expected, as we currently don't now how vehicles are indentified that are able to get information from this endpoint.

By the way - if you are using the library without HA (and if you should do it from the CLI), do you know the ` -j` flag of `bimmerconnected status`?

**Comment by stefan-hausmeister** [comment]
Thanks for the quick answer and especially for the hint with the json-output flag. Very helpful.
