### ISSUE TITLE
[bimmer_connected.models] 'PARTIALLY_LOCKED' is not a valid 'LockState'

### ISSUE THREAD

**Issue by olyashok** [bimmerconnected/bimmer_connected#473]
### Describe the issue

[bimmer_connected.models] 'PARTIALLY_LOCKED' is not a valid 'LockState'

### Expected behavior

[bimmer_connected.models] 'PARTIALLY_LOCKED' is not a valid 'LockState'

### Which Home Assistant version are you using?

2022.7

### What is your region?

North America

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [ ] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

### Anything in the logs that might be useful for us?

```txt
[bimmer_connected.models] 'PARTIALLY_LOCKED' is not a valid 'LockState'
```

**Comment by rikroe** [comment]
Thanks for the report. When `PARTIALLY_LOCKED` is added, the `lock.<your_vehicle>` entity should still be considered as `OPEN`, right?

**Comment by olyashok** [comment]
i guess so
