### ISSUE TITLE
EMISSION_CHECK not an allowed condition based service

### ISSUE THREAD

**Issue by pixel8383** [bimmerconnected/bimmer_connected#490]
### Describe the issue

I am getting the following error:

` 'EMISSION_CHECK' not an allowed condition based service (ConditionBasedService(service_type='EMISSION_CHECK', state=<ConditionBasedServiceStatus.OK: 'OK'>, due_date=datetime.datetime(2062, 9, 1, 0, 0, tzinfo=datetime.timezone.utc), due_distance=ValueWithUnit(value=None, unit=None))) `

HA tells this error appears only once during the startup process.

### Expected behavior

My BMW is a Diesel mild hybrid (320d G21), I am not sure if EMISSION_CHECK is reserved to cars with different engine.

### Which Home Assistant version are you using?

2022.10.x

### What is your region?

Rest of world

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

**Comment by rikroe** [comment]
Thanks for the report! This shouldn't break anything except not giving details about this specific condition based service.

**Comment by pixel8383** [comment]
Yep, I do confirm nothing seems to be broken. Maybe the code could check if the function is available or not before trying to retrieve those data.
