### ISSUE TITLE
Does not work on Python 3.11

### ISSUE THREAD

**Issue by roboticsalign** [bimmerconnected/bimmer_connected#494]
### Describe the issue

Dear all,

thanks for this great library!

Since a few days my script reports an error instead of the status of my vevicle (Mini SE):

`bimmerconnected status -j <mail> <pw> rest_of_world`

This is resulting in the following (shortend) response:

`ValueError: mutable default <class 'bimmer_connected.models.GPSPosition'> for field location is not allowed: use default_factory`

bimmer_connected is executed in docker (latest python:3) and installed via 
`
/usr/local/bin/python -m pip install --upgrade pip > /mnt/ceph/log.txt`

`pip3 install --upgrade bimmer_connected >> /mnt/ceph/log.txt
`

The process/scripts are unchanged since months so I would assume a bug in bimmer_connected resulting in an unhandled error.

Do you need further infos for investigation?

Max

### Expected behavior

I would expect the status in JSON.

### Which Home Assistant version are you using?

--- (just jusing the command line)

### What was the last working version of Home Assistant Core?

-

### What is your region?

Rest of world

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [X] I have a Mini vehicle linked to my account.

### Output of bimmer_connected fingerprint

```txt
Traceback (most recent call last):
  File "/usr/local/bin/bimmerconnected", line 5, in <module>
    from bimmer_connected.cli import main
  File "/usr/local/lib/python3.11/site-packages/bimmer_connected/cli.py", line 16, in <module>
    from bimmer_connected.account import MyBMWAccount
  File "/usr/local/lib/python3.11/site-packages/bimmer_connected/account.py", line 17, in <module>
    from bimmer_connected.vehicle import MyBMWVehicle
  File "/usr/local/lib/python3.11/site-packages/bimmer_connected/vehicle/__init__.py", line 4, in <module>
    from .vehicle import ConnectedDriveVehicle, MyBMWVehicle, VehicleViewDirection  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bimmer_connected/vehicle/vehicle.py", line 14, in <module>
    from bimmer_connected.vehicle.location import VehicleLocation
  File "/usr/local/lib/python3.11/site-packages/bimmer_connected/vehicle/location.py", line 16, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1221, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1211, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 959, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 816, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'bimmer_connected.models.GPSPosition'> for field location is not allowed: use default_factory
```

**Comment by rikroe** [comment]
You're too up to date ;) The error message is caused by some changes with Python 3.11 (we currently only test agains 3.6-3.10).
I checked for a quick fix, but that breaks the tests in many other ways so I'll have to dive much deeper there.

For now the workaround would be using Python 3.10.

**Comment by roboticsalign** [comment]
Thanks for your quick response! I can confirm, that it works as expected with python 3.10.

**Comment by roboticsalign** [comment]
@rikroe: It's still the same error message. I cannot confirm, that the current version works with python 3.11.

Tested versions today: bimmer_connected-0.10.4-py3-none-any.whl and python 3.11.0

**Comment by rikroe** [comment]
> Tested versions today: bimmer_connected-0.10.4-py3-none-any.whl and python 3.11.0

You need `bimmer_connected>=0.11.0` for Python 3.11 (see https://github.com/bimmerconnected/bimmer_connected/releases/tag/0.11.0).
