### ISSUE TITLE
POI via notify is sent to vehicle but not displayed instantly

### ISSUE THREAD

**Issue by mibo-wb-gh** [bimmerconnected/bimmer_connected#496]
### Describe the issue

POI is sent to vehicle but not displayed instantly (it can only be found via map - My BMW)
The last sent POI will only be displayed if the car is locked and then again unlocked a few minutes later and the display powers on again.

### Expected behavior

POI should be displayed within a few seconds on the car screen

### Which Home Assistant version are you using?

core-2022.11.1

### What is your region?

Rest of world

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

### Additional information

It would be interesting if anybody else has noticed this behaviour. It has worked normally some time ago. Also tried with different lat & lon, same problem.

If I send a POI via the My BMW App it will always appear within seconds on the car screen

After_POI_is_sent_only visible_in_map_section_MyBMW

![After_POI_is_sent_only visible_in_map_section_MyBMW](https://user-images.githubusercontent.com/87424844/200859677-0cf20267-7e20-4dc3-9b20-a206daab6904.jpg)

After_car_lock_and_unlock

![After_car_lock_and_unlock](https://user-images.githubusercontent.com/87424844/200859752-fbc9cfcf-b23e-41e5-84c7-fad024fd21de.jpg)

**Comment by rikroe** [comment]
That's an interesting one. I'll try to find some time on the weekend to again capture what the MyBMW app is sending - maybe they add send more information than before that makes this somehow quicker.

Just to confirm: It was working almost instantly before when using the library?

**Comment by mibo-wb-gh** [comment]
Just had a late trip. I left home at 22:18. The POI was sent from HA at 22:19 via an automation.

As I was traveling for a longer distance, the POi appeared at 22:29 on the screen.

My normal travel to work is less than 10 Min. so that could be the reason why I don't get the POI displayed on normal days.

Which would point in your direction regarding a time delay.

Best Regards,
Michael



Mit freundlichen Grüßen,

Michael Bosch
***@***.***



-------- Ursprüngliche Nachricht --------
Von: rikroe ***@***.***>
Datum: 09.11.22 21:03 (GMT+01:00)
An: bimmerconnected/bimmer_connected ***@***.***>
Cc: mibo-wb-gh ***@***.***>, Author ***@***.***>
Betreff: Re: [bimmerconnected/bimmer_connected] POI via notify is sent to vehicle but not displayed instantly (Issue #496)


That's an interesting one. I'll try to find some time on the weekend to again capture what the MyBMW app is sending - maybe they add send more information than before that makes this somehow quicker.

Just to confirm: It was working almost instantly before when using the library?

**Comment by mibo-wb-gh** [comment]
Hi,

I didn’t have bimmerconnected installed for some time, as it always threw an error during install. So I only worked with the main integration BMW Connected Drive.

After giving it another try, I git bimmerconnected installed and funnly enough the POI which I sent from HA are now delivered within a reasonable time frame.

Up to now I have not gotten around to the asyncio part, but as it is working „OK“ at the moment, I would suggest closing the case, as the problem was probably related to the not installed bimmerconnected.

Thanks for your ongoing hard work !

Have a great Christmas and and Happy New Year !

Best Regards,
Michael


Von: rikroe ***@***.***>
Gesendet: Mittwoch, 30. November 2022 21:01
An: bimmerconnected/bimmer_connected ***@***.***>
Cc: mibo-wb-gh ***@***.***>; Author ***@***.***>
Betreff: Re: [bimmerconnected/bimmer_connected] POI via notify is sent to vehicle but not displayed instantly (Issue #496)


Could you try the following in a Python environment with bimmerconnected installed?
We do send all the data needed, but some data is missing which we do not send...

import asyncio



from bimmer_connected.account import MyBMWAccount

from bimmer_connected.api.regions import Regions

from bimmer_connected.api.client import MyBMWClient



from bimmer_connected.const import VEHICLE_POI_URL



USERNAME = ""

PASSWORD = ""



async def main():

    account = MyBMWAccount(USERNAME, PASSWORD, Regions.REST_OF_WORLD)

    await account.get_vehicles()



    vehicle = account.vehicles[0]  # assuming you only have one vehicle in your account, otherwise use account.get_vehicles(VIN)



    async with MyBMWClient(account.config, brand=vehicle.brand) as client:

        await client.post(

            VEHICLE_POI_URL,

            headers={"content-type": "application/json"},

            json={

                "location": {

                    "address": "Bernhard-Grzimek-Allee 1, 60316 Frankfurt am Main",

                    "baseCategoryId": None,

                    "coordinates": {

                        "latitude": 50.1164744,

                        "longitude": 8.697109

                    },

                    "entryPoints": [],

                    "formattedAddress": "Bernhard-Grzimek-Allee 1, 60316 Frankfurt am Main",

                    "locationAddress": {

                        "banchi": None,

                        "chome": None,

                        "city": "Frankfurt am Main",

                        "country": "Deutschland",

                        "countryCode": "DEU",

                        "district": None,

                        "go": None,

                        "houseNumber": "1",

                        "postalCode": "60316",

                        "region": "Frankfurt am Main",

                        "regionCode": None,

                        "settlement": None,

                        "street": "Bernhard-Grzimek-Allee"

                    },

                    "name": "Zoo Frankfurt",

                    "phoneNumber": None,

                    "provider": None,

                    "providerId": None,

                    "providerPoiId": "dropped-pin",

                    "sourceType": None,

                    "type": None,

                    "vehicleCategoryId": None

                },

                "market": None,

                "vin": vehicle.vin

            },

        )



asyncio.run(main())
