### ISSUE TITLE
Cannot install on Windows 10

### ISSUE THREAD

**Issue by TheItschi** [bimmerconnected/bimmer_connected#505]
### Describe the issue

When trying to install the package I receive the following error: 

Microsoft Windows [Version 10.0.19045.2364]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\Windows\system32>pip3 install bimmer_connected
Collecting bimmer_connected
  Using cached bimmer_connected-0.11.0-py3-none-any.whl (45 kB)
Collecting pyjwt>=2.1.0
  Using cached PyJWT-2.4.0-py3-none-any.whl (18 kB)
Collecting pycryptodome>=3.4
  Using cached pycryptodome-3.16.0-cp35-abi3-win32.whl (1.7 MB)
Collecting httpx
  Using cached httpx-0.22.0-py3-none-any.whl (84 kB)
Collecting rfc3986[idna2008]<2,>=1.3
  Using cached rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
Collecting async-generator
  Using cached async_generator-1.10-py3-none-any.whl (18 kB)
Collecting httpcore<0.15.0,>=0.14.5
  Using cached httpcore-0.14.7-py3-none-any.whl (68 kB)
Collecting sniffio
  Using cached sniffio-1.2.0-py3-none-any.whl (10 kB)
Collecting charset-normalizer
  Using cached charset_normalizer-3.0.1-cp36-cp36m-win32.whl (85 kB)
Requirement already satisfied: certifi in c:\python36-32\lib\site-packages (from httpx->bimmer_connected) (2020.4.5.1)
Collecting anyio==3.*
  Using cached anyio-3.6.2-py3-none-any.whl (80 kB)
Collecting h11<0.13,>=0.11
  Using cached h11-0.12.0-py3-none-any.whl (54 kB)
Collecting contextvars>=2.1
  Using cached contextvars-2.4.tar.gz (9.6 kB)
  Preparing metadata (setup.py) ... done
Collecting dataclasses
  Using cached dataclasses-0.8-py3-none-any.whl (19 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.1.1-py3-none-any.whl (26 kB)
Requirement already satisfied: idna>=2.8 in c:\python36-32\lib\site-packages (from anyio==3.*->httpcore<0.15.0,>=0.14.5->httpx->bimmer_connected) (2.9)
Collecting immutables>=0.9
  Using cached immutables-0.19.tar.gz (85 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Using legacy 'setup.py install' for contextvars, since package 'wheel' is not installed.
Building wheels for collected packages: immutables
  Building wheel for immutables (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python36-32\python.exe' 'C:\Python36-32\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\yavuz\AppData\Local\Temp\tmpel8p01cw'
       cwd: C:\Users\yavuz\AppData\Local\Temp\pip-install-plbl7ijy\immutables_2a8056ae1a384fba8ed399d764c119af
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.6
  creating build\lib.win32-3.6\immutables
  copying immutables\map.py -> build\lib.win32-3.6\immutables
  copying immutables\_protocols.py -> build\lib.win32-3.6\immutables
  copying immutables\_testutils.py -> build\lib.win32-3.6\immutables
  copying immutables\_version.py -> build\lib.win32-3.6\immutables
  copying immutables\__init__.py -> build\lib.win32-3.6\immutables
  running egg_info
  writing immutables.egg-info\PKG-INFO
  writing dependency_links to immutables.egg-info\dependency_links.txt
  writing requirements to immutables.egg-info\requires.txt
  writing top-level names to immutables.egg-info\top_level.txt
  reading manifest file 'immutables.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE'
  adding license file 'LICENSE-APACHE'
  adding license file 'NOTICE'
  writing manifest file 'immutables.egg-info\SOURCES.txt'
  copying immutables\_map.c -> build\lib.win32-3.6\immutables
  copying immutables\_map.h -> build\lib.win32-3.6\immutables
  copying immutables\_map.pyi -> build\lib.win32-3.6\immutables
  copying immutables\py.typed -> build\lib.win32-3.6\immutables
  copying immutables\pythoncapi_compat.h -> build\lib.win32-3.6\immutables
  running build_ext
  building 'immutables._map' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for immutables
Failed to build immutables
ERROR: Could not build wheels for immutables, which is required to install pyproject.toml-based projects

I installed VS Build Tools 2022 17.4.3 

### Expected behavior

Installed python package

### Which Home Assistant version are you using?

Standalone for use with Domoticz

### What was the last working version of Home Assistant Core?

None

### What is your region?

Rest of world

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [X] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

### Output of bimmer_connected fingerprint

```txt
None
```

### Anything in the logs that might be useful for us?

```txt
None
```

### Additional information

None

**Comment by rikroe** [comment]
This is not an error with this library, but with a dependency of a dependency.
Also only installing the latest Visual C++ might not work, seems you need more than one C++ version installed.

https://stackoverflow.com/questions/44951456/pip-error-microsoft-visual-c-14-0-is-required

**Comment by rikroe** [comment]
You should also try to install a newer Python version - 3.6 is fully out of support by Python and we don't run tests against it anymore. Domoticz seems to fully support 3.9 which we also support.
