### ISSUE TITLE
China region authentication error

### ISSUE THREAD

**Issue by mjxoicq** [bimmerconnected/bimmer_connected#507]
### Describe the issue

The integration stopped working about 1 week ago.

First several days the logs showed SMS verification code needed, now it only says Authentication error.

### Expected behavior

Authentication successfully

### Which Home Assistant version are you using?

2022.11.4

### What was the last working version of Home Assistant Core?

2022.11.4

### What is your region?

China

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

### Anything in the logs that might be useful for us?

```txt
SYSTEM LOG:

Logger: bimmer_connected.api.authentication
Source: custom_components/bmw_connected_drive/coordinator.py:57
Integration: BMW Connected Drive
First occurred: 21:15:49 (11 occurrences)
Last logged: 21:25:28

Authentication error: {"data":null,"code":499100,"error":true,"msgType":"toast","description":"请前往应用市场获取最新版本"}
```

### Additional information

```txt
INTEGRATION INFORMATION:

正在重试设置: Error communicating with BMW API: Client error '422 Unprocessable Entity' for url 'https://myprofile.bmw.com.cn/eadrax-coas/v2/login/pwd' For more information check: https://httpstatuses.com/422
```

**Comment by ouhaiorg** [comment]
![IMG_20221227_072903](https://user-images.githubusercontent.com/29619015/209588369-f4f9c489-f2e8-4005-bf49-c822ed697411.jpg)

**Comment by rikroe** [comment]
Please see #504
