### ISSUE TITLE
sendpoi fails

### ISSUE THREAD

**Issue by HeraldCoupe** [bimmerconnected/bimmer_connected#512]
### Describe the issue

I'm trying to use the cli to send a poi using the sendpoi command but it fails with this:

_File "C:\Program Files\Python\Python310\lib\site-packages\httpx\_models.py", line 736, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'https://cocoapi.bmwgroup.com/eadrax-dcs/v1/send-to-car/send-to-car'_

Any help is much appreciated.

PS sendpoi_from_address also fails

### Expected behavior

I expect it not to fail and to send the poi to the car.

### Which Home Assistant version are you using?

n/a

### What was the last working version of Home Assistant Core?

n/a

### What is your region?

Rest of world

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [X] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

**Comment by rikroe** [comment]
Still works for me. Are you able to provide the exact CLI command (of course without your credentials) or some other random address that doesn't work either?

**Comment by HeraldCoupe** [comment]
Sure, this is what I'm trying.....

bimmerconnected.exe sendpoi email@gmail.com password rest_of_world myVIN 50.848785 -0.93315

Thanks, your help is much appreciated.

**Comment by rikroe** [comment]
Could you try adding `--name "MyPOI"` to your command after the coordinates?

I marked it as required for the HA component, but seems I didn't change it in the lib (or at least added a dummy value if not given).

**Comment by HeraldCoupe** [comment]
Perfect, that did it.
Thank you so much 😊
