### ISSUE TITLE
Update the debugging information

### ISSUE THREAD

**Issue by colinbendell** [bimmerconnected/bimmer_connected#518]
### Describe the issue

The documentation for debugging the BMW App can be updated using updated tools like mitmproxy's wireguard support. I've documented the approach I've used for my own exploration here: https://github.com/colinbendell/bmw#debugging-the-mybmw-app

### Expected behavior

Update the documentation using [my approach](https://github.com/colinbendell/bmw#debugging-the-mybmw-app). This is a simpler workflow and consistently works even with a virtual device emulation.

**Comment by rikroe** [comment]
Hi, thanks for the heads up! Amazing work you have done there as well, especially with documenting all the quirks.

Two things come to mind:
- Should we have a single "point of truth" for those documentation issues?
- What kind of AVD and OS are you using? I have had issues on Android x86 AVD...

**Comment by colinbendell** [comment]
>Should we have a single "point of truth" for those documentation issues?

Are you thinking about the debugging process or about the APIs themselves? Absolutely. WDYT about a separate repo that documents the current APIs, responses, etc?

>What kind of AVD and OS are you using? I have had issues on Android x86 AVD...

I was using the latest AVD on a x86 macOS and separately on an m1 (arm64)
