### ISSUE TITLE
Feature Request is_vehicle_active

### ISSUE THREAD

**Issue by DatDraggy** [bimmerconnected/bimmer_connected#523]
Hi,
I love the bimmer connected integration. It's quite handy for automations and data history.
Recently I tried to compose an automation that checks if I left any windows/lids open, but noticed that the `is_vehicle_active` state from `bimmer_connected.vehicle.vehicle.MyBMWVehicle` isn't implemented yet. 
Because of that I can only use the last_changed attribute of other states like mileage, which could get annoying the next time I'm in a traffic jam in summer. Lock state isn't a viable option either as my car auto-locks itself once you start driving.
I've had a look through the code myself because I thought surely this isn't too hard to add but sadly I couldn't figure it out properly.

I hope that this'll be a part of a future bimmerconnected version 🙏 

Thank you for all the work regardless

**Comment by gerard33** [comment]
The `is_vehicle_active` [function](https://github.com/bimmerconnected/bimmer_connected/blob/master/bimmer_connected/vehicle/vehicle.py#L215) is always returning `False` at the moment.
I believe that info was available in the past for some cars, but in the current API version that info is not available anymore.

Doublechecking with @rikroe.

**Comment by rikroe** [comment]
Unfortunately cannot give any more insights.

@kriscremers as you own a vehicle with the latest infotainment, are you able to get an fingerprint or HA diagnostic log while somebody is driving your vehicle so we can check?

**Comment by gerard33** [comment]
I have made a fingerprint while driving with my car (iX3 from 2022) and that information is not available for me.
Maybe something only the cars with the latest infotainment support indeed.

**Comment by kriscremers** [comment]
@rikroe I'm the only one driving the vehicle, so I need to figure a way to set that up to gather the information while I do. The fingerprint I have available for a supposedly inactive state doesn't list it (dated 2023-02-21), however. I'd presume this information would be in available in the json data regardless, but flagged FALSE.

**Comment by kriscremers** [comment]
@rikroe I made a fingerprint on my way to work this morning, sadly it doesn't contain said information.
