### ISSUE TITLE
403 Quota Exceeded

### ISSUE THREAD

**Issue by mannibis** [bimmerconnected/bimmer_connected#528]
### Describe the issue

Getting an error saying quota exceeded:

Failed to set up: Client error '403 Quota Exceeded' for url 'https://cocoapi.bmwgroup.us/eadrax-vcs/v4/vehicles' For more information check: https://httpstatuses.com/403

Is this an issue on my end (using remote services too much or refreshing)?  

### Expected behavior

Usage of bimmer_connected to expose MyBMW API to HomeKit via HA without having to re-configure integration or exceeding quota.

### Which Home Assistant version are you using?

2023.4.6

### What was the last working version of Home Assistant Core?

2023.4.6

### What is your region?

North America

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

**Comment by rtuin** [comment]
@mannibis related to https://github.com/bimmerconnected/bimmer_connected/issues/501 ?

**Comment by mannibis** [comment]
Since I added this integration, it seems to needs reconfiguring around 6PM EST. If I try to log in again before 8PM EST it gives me the 403 Quote Exceeded. So it would seem that the quota resets at 8PM EST. Yesterday I did not refresh manually or send any commands myself, so whatever the default polling interval is, it looks like it runs out of requests after about 22 hours. Is 5 minutes the default?

I saw #501 but that issue seemed to be resolved by using the new API endpoints. Do we know what the max requests per 24 hours is for the API? I could try disabling automatic polling and create an automation to poll every 10 minutes or so, but just wanted to get some more info before I did that. Perhaps there are new endpoints again?

**Comment by rikroe** [comment]
I'll try to check if there are new endpoints for US.

In general, a reset a 12am UTC is what weve seen before. In rest of world, polling every 5 minutes still works.

While we don't know the exactly when limiting starts, you could calucate it yourself: number of successful API calls (I.e. Every five minutes) from 12am UTC until first quota exceeded.

**Comment by ChrisCaho** [comment]
I don't know if the times are the same, but otherwise I am seeing the same issue.  Almost daily I get an alert that the bmw integration needs to be reconfigured.  I leave the parm.s as they are and the integration works again.  The integration used to be very stable and is now hit or miss as to actually collecting data.

**Comment by mannibis** [comment]
So I’ve disabled automatic polling and set up an automation to update the Refresh entity every 10 min. I’ll see how that goes and if good I will set a condition to update every 10 min at night and every 5 minutes during the day. Hopefully that will still keep me under the quota.

**Comment by rikroe** [comment]
There are no new endpoints, but the app version changed from 2.12.0 to 3.3.1. Maybe BMW NA is checking on this.
If not, the only chance is to reduce the polling interval. There will be a new release in a couple of days.

Not sure what a sensible polling interval might otherwise be.

**Comment by mannibis** [comment]
Hmmm. So far so good on the 403, but as of 10 minutes ago I'm getting Unavailable. Trying to reload the integration shows:

Retrying setup: Error communicating with BMW API: Server error '500 Internal Server Error' for url 'https://cocoapi.bmwgroup.us/eadrax-vcs/v4/vehicles/state' 

Perhaps BMW server side problems?

**Comment by rikroe** [comment]
With https://github.com/home-assistant/core/pull/91081 merged (will be released in 2023.5), the user agent is updated to the current MyBMW app.
Please let me know this changes something. Otherwise, please test higher polling intervals and let me know if 10, 15 or 20 minutes work reliably for you.

**Comment by mannibis** [comment]
For the past 3 days I haven't gotten the 430 quote exceeded error. I disabled automatic polling and set up 2 automations to update the "Refresh from Cloud" entity. During the daytime I have it set to the normal 5 min and between 11PM and 6AM I have it set to 15 min. So far so good. I also set up a 3rd automation to Reload Config Entry (targeting the entire device) if one of my entities is unavailable for 15 min.

**Comment by rikroe** [comment]
Please let me know if you still get 403 Quota Exceeded on HA >= 2023.5.0. If yes, we need to increase the default polling interval.

**Comment by mannibis** [comment]
I just enabled automatic polling and disabled my automations. Will let you know soon.

**Comment by mannibis** [comment]
Bummer, so it would seem the quota is still in effect, but this time it gave me a more detailed 403 message, even telling me how long until the quota would reset:

`Retrying setup: HTTPStatusError: { "statusCode": 403, "message": "Out of call volume quota. Quota will be replenished in 01:15:51." }` 

This happened around 5:30pm EST. I reverted back to disabling the automatic polling and enabling my automations. That way seems to work without any problems.

**Comment by sweetw0r** [comment]
Same issue for last couple of weeks. Time zone is PST. Haven’t set an automation yet.

**Comment by 5e** [comment]
Has anyone figured out the exact amount of queries you can do in 24 hours? Not using home assistant but I do have a function which runs on a timer every x seconds

**Comment by erpeters3** [comment]
> For the past 3 days I haven't gotten the 430 quote exceeded error. I disabled automatic polling and set up 2 automations to update the "Refresh from Cloud" entity. During the daytime I have it set to the normal 5 min and between 11PM and 6AM I have it set to 15 min. So far so good. I also set up a 3rd automation to Reload Config Entry (targeting the entire device) if one of my entities is unavailable for 15 min.
> 
> I will close the issue for now and will try re-enabling automatic polling when new HA core is released in a couple days with the updated integration. Thanks for your help
> 
> PS: How do I donate? I'd like to show my support and help the cause. This integration saved me a bit of time and frustration over the weekend when I left my keys and phone in the hotel room and was able to unlock my car via my apple watch.

Can you please share exactly how you did this?

**Comment by sincze** [comment]
> Has anyone figured out the exact amount of queries you can do in 24 hours? Not using home assistant but I do have a function which runs on a timer every x seconds
> 
> Edit: Think it's 2020 queries every 24 hours, resetting at 1am GMT 

Are you sure? 
That would mean using cronjob I could use it at least every minute. = 2020/24.

**Comment by 5e** [comment]
> > Has anyone figured out the exact amount of queries you can do in 24 hours? Not using home assistant but I do have a function which runs on a timer every x seconds
> > Edit: Think it's 2020 queries every 24 hours, resetting at 1am GMT
> 
> Are you sure? That would mean using cronjob I could use it at least every minute. = 2020/24.

I'm running a query every 43 seconds and I don't get any too many requests errors.

**Comment by sincze** [comment]
> > > Has anyone figured out the exact amount of queries you can do in 24 hours? Not using home assistant but I do have a function which runs on a timer every x seconds
> > > Edit: Think it's 2020 queries every 24 hours, resetting at 1am GMT
> > 
> > 
> > Are you sure? That would mean using cronjob I could use it at least every minute. = 2020/24.
> 
> I'm running a query every 43 seconds and I don't get any too many requests errors.

Mmm changed my cronjob to every minute after reading your reply with the following result in the evening:
`{ "statusCode": 403, "message": "Out of call volume quota. Quota will be replenished in 03:33:55." }`

**Comment by rikroe** [comment]
Closing this as it should be solved for NA since we increased the default refresh rate to 10 minutes. Please open a new issue if there are still problems.

**Comment by SerhiiAksiutin** [comment]
> should be solved for NA

@rikroe Can you please elaborate? I ran out today.

**Comment by 5e** [comment]
> > should be solved for NA
> 
> @rikroe Can you please elaborate? I ran out today in the official HA integration. Now can't log in even

Might be unrelated but for the past few hours my calls have been messing up, all I've been getting is:

`HTTPStatusError: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>`

Is there just problems on BMW side?

**Comment by SerhiiAksiutin** [comment]
Could be @5e. Their app isn't fetching status either I noticed

**Comment by rikroe** [comment]
> @rikroe Can you please elaborate? I ran out today in the official HA integration. Now can't log in even

Last night's issues where on BMW side.
If you're getting the quota exceeded errors are happening because BMW imposed a limit in how often your allowed to query the API (at least for north America). Calling every 5 minutes lead to this issue. We lowered the frequency to every ten minutes and it works now.

**Comment by steveloughran** [comment]
having other apps (i.e. your phone) may contribute to that load too.
