### ISSUE TITLE
Password gets replaced if auth fails

### ISSUE THREAD

**Issue by nottledim** [bimmerconnected/bimmer_connected#541]
### Describe the issue

I'm trying to reconnect with new credentials.  I add the credentials then if/when auth fails (which it seems to be doing) it reverts to old, now incorrect,  password. It's infuriating, it's one of those stupidly long passwords, it's hard to type but if it's not correct I'll fix it.   Please don't overwrite what I've typed.

### Expected behavior

I expect what I type as credentials  to be accepted even if incorrect.  

### Which Home Assistant version are you using?

Core 2023.6.1

### What was the last working version of Home Assistant Core?

2023.5.4

### What is your region?

Rest of world

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

### Output of bimmer_connected fingerprint

```txt
N/A
```

### Anything in the logs that might be useful for us?

```txt
N/A
```

**Comment by rikroe** [comment]
You mean you enter it in the reconnection dialog of Home Assistant?
The integration does a check if it is able to login with the new credentials and will only persist and save those if it actually worked.
I'm afraid there is not much I can do as this is the default way HA handles reconnect. 

We've had some reports from other BMW owners in north America that they had to change their password again via the MyBMW website. There are a couple of issue threads both in this repo as well as the HA repo on this.
