### ISSUE TITLE
Pillow Import issue 

### ISSUE THREAD

**Issue by rikroe** [bimmerconnected/bimmer_connected#579]
Hello,

I would like to use bimmer_connected on my Raspberry Pi 3B+ but I am can't unitl now. I tried to use the latest python version 3.12.0 but there was an installation error from dependant project. Then I tried Python 3.11.5 (because with this version it is running on my Windows 11 PC). Installation on Raspberry was fine but when I run "from bimmer_connected.account import MyBMWAccount" there is the following error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.11/site-packages/bimmer_connected/account.py", line 10, in <module>
    from bimmer_connected.api.authentication import MyBMWAuthentication
  File "/home/pi/.local/lib/python3.11/site-packages/bimmer_connected/api/authentication.py", line 18, in <module>
    from bimmer_connected.api.utils import (
  File "/home/pi/.local/lib/python3.11/site-packages/bimmer_connected/api/utils.py", line 21, in <module>
    from PIL import Image
  File "/home/pi/.local/lib/python3.11/site-packages/PIL/Image.py", line 82, in <module>
    from . import _imaging as core
ImportError: libtiff.so.6: cannot open shared object file: No such file or directory`

Does someone have an idea what is wrong? Or which Python version on Raspberry Pi is running fine with bimmer_connected?

Thanks for any ideas

_Originally posted by @hube-mic in https://github.com/bimmerconnected/bimmer_connected/discussions/578_

**Comment by subtrEM** [comment]
FWIW, observed this behavior:
bimmer_connected 0.14.1 and beyond installs Pillow (python imaging library) per requirements.
Running bimmerconnected from CLI gives errors, missing components.
Pillow implicitly requires specific (older) versions: libopenjp2-7, libtiff5 (is Pillow still maintained?).
Installing these packages lets the CLI version run.

**Comment by rikroe** [comment]
Are you also running an RPI 3B+? `armhf` or `armv8a`?

**Comment by hube-mic** [comment]
How do I find out armhf or armv8a? It is a 3B+
![image](https://github.com/bimmerconnected/bimmer_connected/assets/111874118/7617772b-a355-47a2-9c72-d95e73763738)

**Comment by subtrEM** [comment]
> Are you also running an RPI 3B+? `armhf` or `armv8a`?

Raspbian Bullseye on raspi 3B (ARMv7); bimmer_connected 0.14.2

**Comment by rikroe** [comment]
Pillow is still maintained and works with new Python versions: https://pillow.readthedocs.io/en/stable/installation.html
Please try installing the required libraries via `apt-get install python3-pil`. It might be that those are not included in the default images for Raspbian.

@gerard33 @Yixi: Should we maybe make the pillow library optional (i.e. not installed by default)? For HA, we still could still include it (as it shipped with HA anyway), but for command line usage it is not necessarily needed.
For chinese accounts, we could raise a specific error message if Pillow is unavailable before first try to login.

**Comment by hube-mic** [comment]
`apt-get install python3-pil` did not help. Nothing to update. Seems already to be installed.

**Comment by hube-mic** [comment]
This is the error message when I try to install bimmerconnected with Python 3.12
![image](https://github.com/bimmerconnected/bimmer_connected/assets/111874118/752bdae9-4d40-44b5-a3ad-d42553c7f231)
Related to pillow, too. But I am not sure if it is the same root cause

**Comment by rikroe** [comment]
Please provide the output of `uname -m`. My current guess is that you're running Raspbian OS 32bit where no wheel (i.e. pre-defined builds) of Pillow are available for. Only arm64/aarch64 is directly built.

Please try installing all required build libraries (taken from https://pillow.readthedocs.io/en/stable/installation.html#external-libraries / Ubuntu).

```
sudo apt-get install libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev \
    libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk \
    libharfbuzz-dev libfribidi-dev libxcb1-dev
```

**Comment by Yixi** [comment]
> Pillow is still maintained and works with new Python versions: https://pillow.readthedocs.io/en/stable/installation.html Please try installing the required libraries via `apt-get install python3-pil`. It might be that those are not included in the default images for Raspbian.
> 
> @gerard33 @Yixi: Should we maybe make the pillow library optional (i.e. not installed by default)? For HA, we still could still include it (as it shipped with HA anyway), but for command line usage it is not necessarily needed. For chinese accounts, we could raise a specific error message if Pillow is unavailable before first try to login.

I think it's fine, currently Pillow is only used in China to handle captcha's.

**Comment by gerard33** [comment]
> > Pillow is still maintained and works with new Python versions: https://pillow.readthedocs.io/en/stable/installation.html Please try installing the required libraries via `apt-get install python3-pil`. It might be that those are not included in the default images for Raspbian.
> > @gerard33 @Yixi: Should we maybe make the pillow library optional (i.e. not installed by default)? For HA, we still could still include it (as it shipped with HA anyway), but for command line usage it is not necessarily needed. For chinese accounts, we could raise a specific error message if Pillow is unavailable before first try to login.
> 
> I think it's fine, currently Pillow is only used in China to handle captcha's.

I am fine with it as well.

**Comment by hube-mic** [comment]
> Please provide the output of `uname -m`. My current guess is that you're running Raspbian OS 32bit where no wheel (i.e. pre-defined builds) of Pillow are available for. Only arm64/aarch64 is directly built.
> 
> Please try installing all required build libraries (taken from https://pillow.readthedocs.io/en/stable/installation.html#external-libraries / Ubuntu).
> 
> ```
> sudo apt-get install libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev \
>     libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk \
>     libharfbuzz-dev libfribidi-dev libxcb1-dev
> ```

uname -m results in armv71

Installing the packages result in this message (sorry for the german screenshot, I enter below the last message so you can copy to translator if required.
![image](https://github.com/bimmerconnected/bimmer_connected/assets/111874118/cb3296de-84a3-41c9-8236-31535c3b6901)
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 libtiff5-dev : Hängt ab von: libtiff-dev (>= 4.0.10-1) soll aber nicht installiert werden
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.

**Comment by rikroe** [comment]
Other than waiting for https://github.com/bimmerconnected/bimmer_connected/pull/583 (or replacing the 32bit OS with 64bit) I have no other idea, sorry.
This is a really nice dependency hell on linux packages for old architectures.

**Comment by rikroe** [comment]
Please try installing 0.14.4 as you would do normally - it should work now.
