### ISSUE TITLE
use_metric_units=False has no impact

### ISSUE THREAD

**Issue by lsiddiquee** [bimmerconnected/bimmer_connected#581]
### Describe the issue

Using the python library I am trying to set ```use_metric_units=False``` however, it is still returning the values in KM however, on the property ```mileage``` ValueWithUnit(value=61366, unit='mi') the actual value is in KM the unit is in miles.

### Expected behavior

Expect that the property will contain the value in the requested unit.

### Which Home Assistant version are you using?

none

### What was the last working version of Home Assistant Core?

none

### What is your region?

Rest of world

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [X] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

**Comment by rikroe** [comment]
Thanks for the report - it might be that the API doesn't consider those values anymore. Needs some investigation in the app communcation with BMW servers.

**Comment by rikroe** [comment]
I remembered something - we already saw that issue in the Home Assistant integration in 2022 (https://github.com/home-assistant/core/pull/75225) and removed/hard coded it there...

**Comment by lsiddiquee** [comment]
Thanks a lot @rikroe for the clarification. Will implement conversion.
