### ISSUE TITLE
Remove previous cars

### ISSUE THREAD

**Issue by Debug1Bug** [bimmerconnected/bimmer_connected#596]
### Describe the issue

I'm on my third BMW now, but the two previous cars are still visible in the integration with apparently no way to remove them. How can I remove the previous cars?

### Expected behavior

A way to remove previous cars - or even better - they should automatically be removed when removed from the BMW app.

### Which Home Assistant version are you using?

2024.1.5

### What is your region?

Rest of world

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

**Comment by rikroe** [comment]
Included in HA 2024.3.
