### ISSUE TITLE
get_vehicle_image suddenly not working

### ISSUE THREAD

**Issue by Jargendas** [bimmerconnected/bimmer_connected#603]
### Describe the issue

Hi, I'm using bimmer_connected as a standalone library, and I suddenly cannot get a vehicle image. It worked as expected two weeks ago. The error shown is:

```
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://cocoapi.bmwgroup.com/eadrax-ics/v3/presentation/vehicles/<VIN>/images?carView=VehicleStatus'
```

The ```<VIN>``` is obviously replaced with my VIN. All other queries seem to work as expected. I think there was an update to the MyBMW app recently, could it be that they changed the API?

### Expected behavior

get_vehicle_image should return a rendered image of the car.

### Which Home Assistant version are you using?

none

### What was the last working version of Home Assistant Core?

none

### What is your region?

Rest of world

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [X] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

**Comment by Xav-74** [comment]
Hi all,

For information, 

File /bimmer_connected/vehicle/vehicle.py L44
`FRONTSIDE = "VehicleStatus"  # also available as AngleSideViewForty`

**VehicleStatus** is now deprecated so you have to use **AngleSideViewForty**

Xav

**Comment by rikroe** [comment]
Thanks for the hint! I'll take this as opportunity to finally create a new release with the new API endpoints from #591 that have now been waiting for a while
