### ISSUE TITLE
parse_datetime reports error on missing lastFetched field

### ISSUE THREAD

**Issue by rleidner** [bimmerconnected/bimmer_connected#610]
### Describe the issue

I get this error:

> unable to parse 'None' using ['%Y-%m-%dT%H:%M:%S.%f%z', '%Y-%m-%dT%H:%M:%S%z', '%Y-%m-%dT%H:%M:%S.%fZ', '%Y-%m-%dT%H:%M:%SZ']

For the car there is no "lastFetched" in attributes.

I think this code in bimmer_connected/utils.py:
`def parse_datetime(date_str: str) -> Optional[datetime.datetime]:
    """Convert a time string into datetime."""
    if not date_str:
        return None
    date_formats = ["%Y-%m-%dT%H:%M:%S.%f%z", "%Y-%m-%dT%H:%M:%S%z", "%Y-%m-%dT%H:%M:%S.%fZ", "%Y-%m-%dT%H:%M:%SZ"]
`
should rather be:
`def parse_datetime(date_str: str) -> Optional[datetime.datetime]:
    """Convert a time string into datetime."""
    if not date_str or date_str = "None":
        return None
    date_formats = ["%Y-%m-%dT%H:%M:%S.%f%z", "%Y-%m-%dT%H:%M:%S%z", "%Y-%m-%dT%H:%M:%S.%fZ", "%Y-%m-%dT%H:%M:%SZ"]
`

The calling vehicle/vehicle.py converts None to "None"...

### Expected behavior

avoid the error message

### Which Home Assistant version are you using?

bimmerconnected cli

### What was the last working version of Home Assistant Core?

n/a

### What is your region?

Rest of world

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

**Comment by rikroe** [comment]
Thanks, hope the PR solves it.
