### ISSUE TITLE
HA - Unable to update charging_profile

### ISSUE THREAD

**Issue by brave0d** [bimmerconnected/bimmer_connected#621]
### Describe the issue

Within my home assistant I am seeing a lot of errors like that:

```
Logger: bimmer_connected.vehicle.vehicle
Source: components/bmw_connected_drive/coordinator.py:58
First occurred: 21:16:43 (8 occurrences)
Last logged: 21:51:48

Unable to update charging_profile - (TypeError) argument of type 'NoneType' is not iterable
```

It is X3 diesel version, so no any charging there or hybrid etc.

Maybe it should be reported to HA directly? Not sure, sorry... 

### Expected behavior

No erros

### Which Home Assistant version are you using?

2024.5.5

### What is your region?

Rest of world

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

**Comment by rikroe** [comment]
Already fixed (https://github.com/home-assistant/core/pull/118179) and will be included in 2024.6.
