### ISSUE TITLE
ModuleNotFoundError: No module named 'importlib.metadata'

### ISSUE THREAD

**Issue by zurnib** [bimmerconnected/bimmer_connected#632]
### Describe the issue

Hi,

when executing 'bimmerconnected' I get the above mentioned error. Searching google gives the following hint:

> instead of
> 
> `import importlib.metadata`
> write
> 
> ```
> from importlib_metadata import metadata
> if importlib_metadata module is not installed then first install via
> ```
> 
> pip install importlib-metadata
> detail: [https://stackoverflow.com/a/59734959/19428695]

### Expected behavior

bimmerconnected is supposed to run

### Which Home Assistant version are you using?

none

### What is your region?

Rest of world

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.
- [ ] I have a Toyota Supra vehicle linked to my account.

**Comment by rikroe** [comment]
You are probably using a Python version < 3.8, which we do not support. Since Python 3.8, `importlib.metadata` is part of the core Python distribution.

See https://stackoverflow.com/a/76547876.

**Comment by zurnib** [comment]
Thanks - unfortunately installation of 3.12.x didn't work, but that's another problem...I'll keep trying
