### ISSUE TITLE
HTTPStatusError

### ISSUE THREAD

**Issue by sshaikh** [bimmerconnected/bimmer_connected#651]
### Describe the issue

Since last week I've been seeing the following via the CLI:

```
❯ bimmerconnected status $USERNAME $PASSWORD $REGION
MyBMWAPIError due to HTTPStatusError: invalid_request - The request is missing a required parameter, includes an unsupported parameter value (other than grant type), repeats a parameter, includes multiple credentials, utilizes more than one mechanism for authenticating the client, or is otherwise malformed
Found 1 vehicles: xxx
```

It then returns okay

### Expected behavior

For no error to occur.

### Which Home Assistant version are you using?

cli

### What was the last working version of Home Assistant Core?

cli

### What is your region?

Rest of world

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.
- [ ] I have a Toyota Supra vehicle linked to my account.

### Additional information

I think this has happened since the BMW outage this week but can't be sure.

**Comment by sshaikh** [comment]
And of course now it's working okay. FWIW I had disabled the HA integration during the downtime and went through all sorts of password changes since so I'm not sure how to recreate this. Happy to close unless you want further investigation.

**Comment by rikroe** [comment]
Thanks for mentioning and thanks for the patience. I guess this comes up when logging in with the `refresh_token` stored locally does not work (or the refresh token is expired/revoked).

As you mentioned it works again on both on cmd and in HA, I'll close it.
