### ISSUE TITLE
Only receiving 11 entities on cooper se, no battery status in there

### ISSUE THREAD

**Issue by frankrox** [bimmerconnected/bimmer_connected#658]
### Describe the issue

I seem to be missing sensor data for a mini cooper se 2024 (EV). Things like battery status are not shown.

### Expected behavior

 I would like to at the very least see the current battery percentage for this car.

### Which Home Assistant version are you using?

2024.8.1

### What is your region?

Rest of world

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [X] I have a Mini vehicle linked to my account.
- [ ] I have a Toyota Supra vehicle linked to my account.

### Anything in the logs that might be useful for us?

below are the entities which are showing up. 
![haminicooperse](https://github.com/user-attachments/assets/5ca52e88-3595-42ae-afbd-cec9c34dc693)

**Comment by rikroe** [comment]
Please provide the full diagnostics file from HA's device page.
However I'm on vacation so it'll be some time to have a deeper look.

**Comment by frankrox** [comment]
Thanks! 

It is attached.
[bmw_connected_drive-01J89PNXSEKW5RV4TQ81R14BDJ-Cooper SE-20dac134933ad190c192a5d0d37ceffe.json](https://github.com/user-attachments/files/17085261/bmw_connected_drive-01J89PNXSEKW5RV4TQ81R14BDJ-Cooper.SE-20dac134933ad190c192a5d0d37ceffe.json)

**Comment by frankrox** [comment]
solved, i think i used the bmw instead of mini integration and I didn't use the main account for the car.. Using the mini integration and the main account gives 38 entities.

**Comment by rikroe** [comment]
The main difference would be main/second account as the mini integration basically only forwards your login data to the BMW integration.

But thanks for the fingerprint, I will have a look if there is a warning or so that could be printed.
