### ISSUE TITLE
add remote service: send POI

### ISSUE THREAD

**Issue by m1n3rva** [bimmerconnected/bimmer_connected#66]
You can send a point of interest (POI) to the vehicle. Add this as a remote service.

see https://github.com/edent/BMW-i-Remote#send-poi

**Comment by m1n3rva** [comment]
I tried to implement this but I always get "Formparameter 'data' is not valid!" from the server. Does anyone know the exact format of the request body? 

My best guess right now is:
```json
{
  "data" : 
  { 
    "lat" : 1.23,
    "lon" : 2.34
  }
}
```

**Comment by EgleEU** [comment]
According to https://github.com/edent/BMW-i-Remote#body
Body
body={
	"poi": {
		"city": "abc",
		"lat": nn.nnn,
		"lon": nn.nnn,
		"name": "name",
		"rating": -1,
		"postalCode": "12345",
		"street": "Musterstr. 6"
	}
}
I would like to import of third-party POI (list of charging station) to navigation system of my BMW i3.

**Comment by m1n3rva** [comment]
@EgleEU This is the first thing I've tried, but it did not work. It seems the server expects a `data` tag on the first level, but I have not clue on what the `data` tag then should contain...

**Comment by ntruchsess** [comment]
replace 'body' by 'data' will work. Set 'Content-Type' to 'application/x-www-form-urlencoded'. Don't forget to actually urlencode the json right of data= as the body of the POST-request is taken as urlencoded fields of a form (the urlencoded json being the value of field 'data')

**Comment by m1n3rva** [comment]
@ntruchsess Thx for the hints 👍 !
So these two versions seem to work 
```
# data = <json string>
data={"poi": {"lat": 10.0, "lon": 20.0}}
```
and with url encoding:
```
# data = urlencode({"data":<json string>})
data=%7B%22poi%22%3A+%7B%22lat%22%3A+10.0%2C+%22lon%22%3A+20.0%7D%7D
```

Then the server answers with HTTP status code 204 ("No content"). So this is the best result yet 🎆 
I'll have to check, what really arrived in my car 😄

**Comment by ntruchsess** [comment]
I can confirm: 204 (no content) is the expected result for a valid sendpoi-request.

**Comment by rikroe** [comment]
Would it also be possible to make latitude and longitude optional and only send city, postal_code and street? I am aware that this might lead to incorrect results (at least address data that cannot be parsed by the car). However I would like to have at least the possibility to do this.

**Comment by gerard33** [comment]
Part of PR #98.
