### ISSUE TITLE
Client Authentication Failed

### ISSUE THREAD

**Issue by kpridgeon** [bimmerconnected/bimmer_connected#661]
### Describe the issue

Unable to connect to retrieve the bmw vehicles.

Receive this error message:
site-packages/bimmer_connected/api/utils.py", line 89, in handle_httpstatuserror
    raise _ex_to_raise(_err_message) from ex
bimmer_connected.models.MyBMWAuthError: HTTPStatusError: invalid_client - Client authentication failed (e.g., login failure, unknown client, no client authentication included or unsupported authentication method)

### Expected behavior

Yesterday it was able to retrieve the bmw information.

### Which Home Assistant version are you using?

None

### What is your region?

North America

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [X] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.
- [ ] I have a Toyota Supra vehicle linked to my account.

### Output of bimmer_connected fingerprint

```txt
MyBMWAuthError due to HTTPStatusError: invalid_client - Client authentication failed (e.g., login failure, unknown client, no client authentication included or unsupported authentication method)
MyBMWAuthError: HTTPStatusError: invalid_client - Client authentication failed (e.g., login failure, unknown client, no client authentication included or unsupported authentication method)
```

**Comment by jarjarfinks** [comment]
Same here. Have had no issues until now. 2024 M440i here

**Comment by rikroe** [comment]
Whats your location (US/rest of world)?

**Comment by jarjarfinks** [comment]
> Whats your location (US/rest of world)?

US

**Comment by Berzerker** [comment]
Also having this issue

**Comment by rikroe** [comment]
Quick update I posted at https://github.com/home-assistant/core/issues/128598
> I was only able to confirm that currently authentication to North America is not possible. Rest of world still seems fine.
> 
> Unfortunately, I won't have the chance to look into it until next week (traveling).

**Comment by rikroe** [comment]
Another update from https://github.com/home-assistant/core/issues/128598

> BMW have started using **hCaptcha** to protect their logins. Even if it doesn't show during login in the app, a captcha check is done in the background.
> 
> It seems that when no valid captcha token is preset, the login will be denied.
> 
> From a very quick check I have no immediate idea how to solve this (except using external captcha solver services with cost money).
