### ISSUE TITLE
Changes to httpx SSL cert handling

### ISSUE THREAD

**Issue by rikroe** [bimmerconnected/bimmer_connected#688]
Hi,

I've just tried out bimmer_connected as a workaround for evcc.io not supporting the new captcha. I have bimmerconnected working on my MacBook, but I need to get it running on my Raspberry Pi for evcc to be able to use it.

On my RPi, when I run:

bimmerconnected status MYEMAIL MYPASS -v MYVIN rest_of_world --json --hcaptcha THE_CAPTURE_TOKEN

I get:

Traceback (most recent call last):
  File "/usr/local/bin/bimmerconnected", line 5, in <module>
    from bimmer_connected.cli import main
  File "/usr/local/lib/python3.9/dist-packages/bimmer_connected/cli.py", line 16, in <module>
    from bimmer_connected.account import MyBMWAccount
  File "/usr/local/lib/python3.9/dist-packages/bimmer_connected/account.py", line 11, in <module>
    from bimmer_connected.api.authentication import MyBMWAuthentication
  File "/usr/local/lib/python3.9/dist-packages/bimmer_connected/api/authentication.py", line 44, in <module>
    class MyBMWAuthentication(httpx.Auth):
  File "/usr/local/lib/python3.9/dist-packages/bimmer_connected/api/authentication.py", line 57, in MyBMWAuthentication
    verify: httpx._types.VerifyTypes = True,
AttributeError: module 'httpx._types' has no attribute 'VerifyTypes'

I've Googled that error and don't get any results. I have not done any Python for a very, very long time so I'm out of my depth here.

python -V reports:

Python 3.9.2

and it appears I have version 0.28.0 of httpx. I randomly tried 0.24.0 as well but it makes no difference.

_Originally posted by @pdonovan in https://github.com/bimmerconnected/bimmer_connected/discussions/687_

**Comment by rikroe** [comment]
Thanks for letting me know. There was a change in 0.28 for which I need to adjust.

Try 0.27.0, this should work.

**Comment by pdonovan** [comment]
I tried with 0.27.0 and get exactly the same error. I edited my local files to match commit 97e1a1dbb0c9b3b0a2d13157efbc824a44f76840 and got an error:
`TypeError: unsupported operand type(s) for |: 'type' and 'type'`

It looks like that's a feature that's not supported in python 3.9. To fix it locally I added:
`from __future__ import annotations` to the start of the imports in those files. After doing that it works OK.

**Comment by rikroe** [comment]
Thanks for bringing it up, I missed this initially. See https://github.com/bimmerconnected/bimmer_connected/pull/693/commits/678ee401066546e3836f30f80d47d467fbcd0745 where I went to more traditional route with `typing.Union`.

So next release of the lib will work ;)

**Comment by grasshide** [comment]
Sorry to bring this up again @rikroe but I still have this issue with the latest version:

```
python version: 3.13.0 (main, Nov 12 2024, 06:05:34) [GCC 12.2.0]
bimmer version: 0.17.1
httpx version: 0.28.0


  File "/usr/local/lib/python3.13/site-packages/bimmer_connected/api/authentication.py", line 57, in MyBMWAuthentication
    verify: httpx._types.VerifyTypes = True,
            ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'httpx._types' has no attribute 'VerifyTypes'. Did you mean: 'ProxyTypes'?
```
