### ISSUE TITLE
Python bug with strptime

### ISSUE THREAD

**Issue by FilipDem** [bimmerconnected/bimmer_connected#692]
### Describe the issue

As described in [https://bugs.python.org/issue27400](https://bugs.python.org/issue27400), there is a bug in python when using it in embedded python. Calling `datetime.datetime.strptime`, could result in `TypeError: 'NoneType' object is not callable`.
Currently I am running into that case with my integration in Domoticz on https://github.com/bimmerconnected/bimmer_connected/blob/master/bimmer_connected/utils.py#L32, because of trying to get the timestamp of the data through https://github.com/bimmerconnected/bimmer_connected/blob/master/bimmer_connected/vehicle/vehicle.py#L224.

A workaround is described in the bug report and sample code can be found below.
Currently I implemented the workaround by not using the vehicle `timestamp` property, but rather getting the timestamp by parsing the vehicle data myself from the https://github.com/bimmerconnected/bimmer_connected/blob/master/bimmer_connected/vehicle/vehicle.py#L86.
```
def DateStringtoDateTime(DateStr, DateFrm='%Y-%m-%d %H:%M:%S'):
    Datim = None
    if DateStr:
        try:
            Datim = datetime.strptime(DateStr, DateFrm)
        except TypeError:
            try:
                import time
                Datim = datetime(*(time.strptime(DateStr, DateFrm)[0:6]))
            except:
                pass
    return Datim

```

### Expected behavior

Would it be possible to implement this workaround in the https://github.com/bimmerconnected/bimmer_connected/blob/master/bimmer_connected/utils.py#L32?

### Which Home Assistant version are you using?

(using Domoticz)

### What is your region?

Rest of world

### MyBMW website

- [ ] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [ ] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.
- [ ] I have a Toyota Supra vehicle linked to my account.

**Comment by rikroe** [comment]
I thought this error was only applicable to embedded Pythons <= 3.7 (which we don't support anymore)?

What version are you running?

**Comment by FilipDem** [comment]
Bullseye... So python 3.9... Far from the 3.12 :-(.
It would help me, but understand your reasoning as I have a workaround. I just hope that the structure of the data won't change then. I will respect whatever decision you make.
Filip

**Comment by rikroe** [comment]
Hi @FilipDem, can you check if #697 fixes your issue?

**Comment by FilipDem** [comment]
Hey! Thanks a lot!
This works now (and also the location works again following the discussion https://github.com/bimmerconnected/bimmer_connected/discussions/694).
