### ISSUE TITLE
can't authenticate to bimmer connected

### ISSUE THREAD

**Issue by dougstarfish** [bimmerconnected/bimmer_connected#700]
### Describe the issue

I was trying to revive and get the latest version of bimmer_connected to see if I could set charging profiles for my Mini Cooper yet. I'm running into auth issues. I just did a git clone of latest

here's bimmerconnected cli:
bimmerconnected status --captcha-token $CAPTCHA_TOKEN $USERNAME $PASSWORD north_america
MyBMWAuthError due to HTTPStatusError: invalid_client - Client authentication failed (e.g., login failure, unknown client, no client authentication included or unsupported authentication method)
MyBMWAuthError: HTTPStatusError: invalid_client - Client authentication failed (e.g., login failure, unknown client, no client authentication included or unsupported authentication method)

If I use python example (previously worked in older version about 9 months ago)
>>> account = MyBMWAccount(USERNAME, PASSWORD, Regions.NORTH_AMERICA, hcaptcha_token=CAPTCHA_TOKEN)
>>> asyncio.run(account.get_vehicles())
MyBMWAuthError due to HTTPStatusError: invalid_client - Client authentication failed (e.g., login failure, unknown client, no client authentication included or unsupported authentication method)
Traceback (most recent call last):
  File "/home/doug/git/bimmer_connected/bimmer_connected/api/authentication.py", line 411, in raise_for_status_event_handler
    response.raise_for_status()
  File "/usr/lib/python3.11/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'https://login.bmwusa.com/gcdm/oauth/authenticate'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

I can auth to bmwusa.com web page successfully with same username and password, so I know it's not a bad username or password. The captcha token is fresh.

### Expected behavior

successful api call

### Which Home Assistant version are you using?

bimmer_connected-0.17.2.dev5

### What is your region?

North America

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [X] I have a Mini vehicle linked to my account.
- [ ] I have a Toyota Supra vehicle linked to my account.

**Comment by dougstarfish** [comment]
doug@omni1:/home/doug/git/bimmer_connected$ bimmerconnected --debug status --captcha-token $CAPTCHA_TOKEN $USERNAME $PASSWORD north_america
DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:httpx:load_verify_locations cafile='/usr/lib/python3.11/site-packages/certifi/cacert.pem'
DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:httpx:load_verify_locations cafile='/usr/lib/python3.11/site-packages/certifi/cacert.pem'
DEBUG:bimmer_connected.api.authentication:Authenticating with MyBMW flow for North America & Rest of World.
DEBUG:httpcore.connection:connect_tcp.started host='cocoapi.bmwgroup.us' port=443 local_address=None timeout=30.0 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0xfffffc7feb7a7fd0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0xfffffc7feb74deb0> server_hostname='cocoapi.bmwgroup.us' timeout=30.0
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0xfffffc7feb7a7cd0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Date', b'Mon, 02 Dec 2024 02:18:22 GMT'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Content-Length', b'565'), (b'Connection', b'keep-alive'), (b'x-correlation-id', b'5b8f6e96-bb72-4f0b-ad9e-4684c264f5b2'), (b'bmw-correlation-id', b'5b8f6e96-bb72-4f0b-ad9e-4684c264f5b2'), (b'x-cluster-mock-used', b'false'), (b'Strict-Transport-Security', b'max-age=31536000; includeSubDomains'), (b'X-Content-Type-Options', b'nosniff'), (b'Content-Security-Policy', b"default-src 'self'"), (b'Request-Context', b'appId=cid-v1:3447961e-979e-4bb9-9a5c-2a729e41a4bb'), (b'x-azure-ref', b'20241202T021822Z-174f7845968cdxdrhC1EWRg0en00000013vg000000000c4a'), (b'X-Cache', b'CONFIG_NOCACHE'), (b'Accept-Ranges', b'bytes')])
INFO:httpx:HTTP Request: GET https://cocoapi.bmwgroup.us/eadrax-ucs/v1/presentation/oauth/config "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:connect_tcp.started host='login.bmwusa.com' port=443 local_address=None timeout=30.0 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0xfffffc7fe7115c90>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0xfffffc7feb74deb0> server_hostname='login.bmwusa.com' timeout=30.0
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0xfffffc7fe7115b50>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 401, b'Unauthorized', [(b'content-type', b'application/json'), (b'x-c2b-pwpolicyconform', b'true'), (b'access-control-allow-headers', b'Authorization, Origin, X-c2b-Authorization, X-c2b-mTAN, X-Requested-With, X-c2b-Sender-Id, X-c2b-External-Id, Content-Type, Accept, Cache-Control, KeyId, x-dtc, deviceName, loginId, clientId, X-C2b-Api-Key, hcaptchatoken'), (b'access-control-max-age', b'3628800'), (b'access-control-allow-credentials', b'true'), (b'access-control-allow-methods', b'POST, GET, OPTIONS, PUT, DELETE, HEAD'), (b'referrer-policy', b'same-origin'), (b'x-xss-protection', b'0'), (b'x-content-type-options', b'nosniff'), (b'x-frame-options', b'SAMEORIGIN'), (b'x-c2b-request-id', b'0f41ef21-2867-4912-aac8-2d74fc8f0ae5298710999'), (b'x-request-id', b'd4e82a7f-bdbf-4bfc-a1d8-879ec1ee99d3'), (b'Content-Length', b'190'), (b'date', b'Mon, 02 Dec 2024 02:18:22 GMT'), (b'via', b'1.1 google'), (b'Alt-Svc', b'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000')])
INFO:httpx:HTTP Request: POST https://login.bmwusa.com/gcdm/oauth/authenticate "HTTP/1.1 401 Unauthorized"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
ERROR:bimmer_connected.api.authentication:MyBMWAuthError due to HTTPStatusError: invalid_client - Client authentication failed (e.g., login failure, unknown client, no client authentication included or unsupported authentication method)
DEBUG:httpcore.connection:close.started

**Comment by jeterke** [comment]
Same here. I have 2 cars with 2 accounts and same problem on both since 30-Nov. 
I tried all the tricks in the book like changing passwords couple times etc. 
But I keep getting this authentication failed error. While the BMW App is still working fine.

**Comment by dj0abr** [comment]
Same here in Germany. Authentication worked well, but since a few weeks I just get this authentication failed error. The App works fine.

**Comment by sincze** [comment]
@rikroe  just to be sure. The following should be able to work right with a newly created captcha. Version: 0.17.2

`/home/pi/.local/bin/bimmerconnected status i4@mybmw.nl mypassword- rest_of_world --captcha-token P1_********`

**Comment by rikroe** [comment]
Yes this should work. I have just verified this with a clean login for rest_of_world as well.

```
~/bimmer_connected$ bimmerconnected --oauth-store local.json status -j me@email.com 'My&Pa55word' rest_of_world --captcha-token P1_eyJ0eXAiOiJKV1QiLCJhbGciO...8Rzj5ecyk
[{"data": {"attributes": {"model": "320d xDrive", ...
```

Although it might sound silly, have you double checked that you are generating the captcha the correct region?
Is the captcha 100% correctly copied? I have had issues with this myself.

Note that I have to put my password into single quotes `'` as the `&` symbol otherwise gets intepreted by bash. You can test this using `echo` and your password (example below):

```
# works with quotes
echo 'My&Pa55word' 
My&Pa55word

# but not without
echo My&Pa55word
[1] 308006
My
Pa55word: command not found
[1]+  Done                    echo My
```

**Comment by dougstarfish** [comment]
resolved
