### ISSUE TITLE
Home Assistant captcha token link is missing

### ISSUE THREAD

**Issue by Ein-nor** [bimmerconnected/bimmer_connected#717]
### Describe the issue

Hi,

i´m trying to install BMW Connected Drive → region: rest_of_world.
I don't get a link for the captcha token.

![CleanShot 2024-12-28 at 21 07 26@2x](https://github.com/user-attachments/assets/a387334e-c0ee-4056-a6be-41fce944afa8)

### Expected behavior

Get a link to receive a captcha token.

### Which Home Assistant version are you using?

core-2024.12.5

### What is your region?

Rest of world

### MyBMW website

- [x] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.
- [ ] I have a Toyota Supra vehicle linked to my account.

**Comment by gerard33** [comment]
You are using the custom component (as shown by the BETA part in your screenshot). That version is not up to date so please make sure you use the version from Home Assistant --> delete `bmw_connected_drive` folder in the `config/custom_components` folder and restart HA.

Then you can follow the [documentation](https://www.home-assistant.io/integrations/bmw_connected_drive/#captcha-token-second-step-only-for-north-america-and-rest-of-world).

**Comment by Ein-nor** [comment]
Thank you, it worked.
