### ISSUE TITLE
add missing argument

### ISSUE THREAD

**Issue by m1n3rva** [bimmerconnected/bimmer_connected#73]
Add these attributes that are present in the status.json, but not yet in the API:
```
    "positionLight" : "OFF",
    "chargingConnectionType" : "CONDUCTIVE",
    "chargingInductivePositioning" : "NOT_POSITIONED",
    "DCS_CCH_Ongoing" : false,
    "DCS_CCH_Activation" : "NA",
    "steering" : "LH",
    "connectionStatus" : "CONNECTED",
    "lastChargingEndReason" : "UNKNOWN",
    "lastChargingEndResult" : "UNKNOWN",
    "singleImmediateCharging" : false,

```

**Comment by lawtancool** [comment]
what is a position light even...
Doesn't the parking light mark your position on the side of the road?
Or, is this the headlight flashing function?

**Comment by m1n3rva** [comment]
@lawtancool No idea. But i'll try to figure that out...

**Comment by lawtancool** [comment]
I think `"chargingInductivePositioning"` is probably for a wireless charging accessory that hasn't released yet, that charges the car via a wireless induction pad under the car. BMW has teased this for a while, but I don't think you can buy one yet.

Maybe `"DCS_CCH_Ongoing"` and `"DCS_CCH_Activation"` are for some sort of paid charging network? (like one run by BMW, maybe that's why they have a "activation" thing)

**Comment by m1n3rva** [comment]
No clue what these values are used for. If anyone known the semantics or has a use case, please let me know...

**Comment by gerard33** [comment]
@m1n3rva 
Is this still on the list?
Adding the attributes `lastChargingEndResult` and `connectionStatus` would make some cleanup possible as discussed [here](https://github.com/home-assistant/home-assistant/pull/14293#pullrequestreview-117901777) for these parts:

- https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/binary_sensor/bmw_connected_drive.py#L136
- https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/binary_sensor/bmw_connected_drive.py#L140
- https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/binary_sensor/bmw_connected_drive.py#L177

**Comment by m1n3rva** [comment]
@gerard33 OK, I can have a look at this.

**Comment by gerard33** [comment]
Clean-up for `lastChargingEndResult` and `connectionStatus` added via 
https://github.com/home-assistant/home-assistant/pull/26098.
