### ISSUE TITLE
Unlock won’t work on all cars

### ISSUE THREAD

**Issue by bdwilson** [bimmerconnected/bimmer_connected#77]
If BMW requires the security “answer” to unlock, unlock will fail. Need additional parameter in config to support the use of security word. More info can be found here. 

https://github.com/edent/BMW-i-Remote/blob/master/README.md#unlock-the-doors

**Comment by m1n3rva** [comment]
@bdwilson hmm interesting. Never seen that before. This seems to only affect certain vehicles.

Where does the `BMW_ACCOUNT_SECURITY_QUESTION_ANSWER` come from? Do you (as a user) have that? Is the provided by BMW? Or can you configure this somehow?

**Comment by bdwilson** [comment]
Here's an example of how that's implemented, you need to pass an additional parameter:
    def executeService2(self, vin, serviceType, bmwSkAnswer):
        """
        Post a request for the specified service. e.g.

            print c.executeService(vin, 'DOOR_UNLOCK')

        """
        return self.call("/user/vehicles/{}/executeService".format(vin),
            {'serviceType': serviceType,
			 'bmwSkAnswer': bmwSkAnswer})

**Comment by m1n3rva** [comment]
@bdwilson I just added the feature as your requested: #92 

Can you have a look if that works? Then I would merge the change...

**Comment by Partizan7676** [comment]
confirm for my F85. lot of things not working. only GPS, lid and flashes....

**Comment by Partizan7676** [comment]
@m1n3rva if you would like - can test what you need.

**Comment by gerard33** [comment]
Part of PR #92.
