### ISSUE TITLE
Sunroof for i3 not showing up under windows

### ISSUE THREAD

**Issue by jitmonlee** [bimmerconnected/bimmer_connected#81]
Hi, 

I can see if my windows/doors are open or not but I can't see sunroof status at all. Is anyone able to update this?

https://bimmer-connected.readthedocs.io/en/latest/_modules/bimmer_connected/state.html#VehicleState

According to the link above, the sunroof should be included in the windows status - could be a bug?

Thanks in advance.

**Comment by jitmonlee** [comment]
`LIDS = ['doorDriverFront', 'doorPassengerFront', 'doorDriverRear', 'doorPassengerRear',
        'hood', 'trunk']

WINDOWS = ['windowDriverFront', 'windowPassengerFront', 'windowDriverRear', 'windowPassengerRear', 'rearWindow',
           'sunroof']`

**Comment by m1n3rva** [comment]
Hi @jitmonlee,

can you please provide a fingerprint for your vehicle as explained here?
https://github.com/m1n3rva/bimmer_connected#data-contributions

I would need to see what data the server sends for your vehicle to find out why you can't see the sunroof status...

**Comment by jitmonlee** [comment]
Thanks Guys, I'm just waiting for the fix( https://community.home-assistant.io/t/bmw-connecteddrive-component/39569/295?u=jitmonlee) and then I'll check this out.

**Comment by gerard33** [comment]
@jitmonlee any updates on this?

**Comment by jitmonlee** [comment]
Hi, yes since the updated its started to appear. Thank you!

**Comment by gerard33** [comment]
That's good to hear.

Just to be clear, there wasn't any update for the sunroof part, it was already there for quite a while now :sunglasses:

**Comment by jitmonlee** [comment]
Odd, something was certainly not working for me. That sunroof info was not coming through before, and I've also now got some more entities showing extra things eg "reason for end of charge".
