### ISSUE TITLE
[Improvement] Avoid errors in the log for cars that are not supported

### ISSUE THREAD

**Issue by gerard33** [bimmerconnected/bimmer_connected#96]
@m1n3rva 
Would be good to have another look at the `"lscType": "NOT_SUPPORTED"` solution we have discussed earlier [here](https://github.com/m1n3rva/bimmer_connected/issues/62#issuecomment-386412788) and [here](https://github.com/m1n3rva/bimmer_connected/pull/74#issuecomment-387207067).

As is shown [here](https://github.com/m1n3rva/bimmer_connected/issues/95) the HA log is showing a lot of errors when the car has no relevant data to show.

We should be able to avoid that and show a neat message in the log stating that it is an unsupported car.

**Comment by m1n3rva** [comment]
@gerard33 I'm already checking the `lscType` in `Vehicle.available_attributes`. This function will give you all the attributes that are available for this vehicle. So if you use only show attributes listed there, you should be safe.

What would you like the API to look like? What should the library do when `"lscType": "NOT_SUPPORTED"`?

**Comment by gerard33** [comment]
The relevant HA code for the `binary sensors` as an example is as [follows](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/binary_sensor/bmw_connected_drive.py#L42).

So I don't check if the attributes are available in `Vehicle.available_attributes`. The same approach goes for the `sensors` in HA as shown [here](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/sensor/bmw_connected_drive.py#L56).

But to my understanding this check should be enough. Because if the car is not supported then only the available sensors should be added.

But in #95 the logs shows a.o. the following error:
```
 File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/binary_sensor/bmw_connected_drive.py", line 117, in device_state_attributes
    result['lights_parking'] = vehicle_state.parking_lights.value
AttributeError: 'NoneType' object has no attribute 'value'
```

I would not suspect the `parking_lights` binary sensor to be added due to the current checks?
What's your opinion on this?
